---@meta

---@class ABP_Archway_B_Merged_C : ABP_OMDTrapGrid_C
---@field SM_MERGED_Archway_B_Pillar_A1 UStaticMeshComponent
---@field SM_MERGED_Archway_B_Pillar_A UStaticMeshComponent
---@field Box_Collision4 UBoxComponent
---@field Box_Collision3 UBoxComponent
---@field Box_Collision2 UBoxComponent
---@field SM_MERGED_Archway_B_Arch UStaticMeshComponent
---@field Wall09 URSTTrapGridBoxComponent
---@field Wall08 URSTTrapGridBoxComponent
---@field Box_Collision1 UBoxComponent
---@field Wall07 URSTTrapGridBoxComponent
---@field Wall06 URSTTrapGridBoxComponent
---@field Wall05 URSTTrapGridBoxComponent
---@field Wall04 URSTTrapGridBoxComponent
---@field Wall03 URSTTrapGridBoxComponent
---@field Wall02 URSTTrapGridBoxComponent
---@field Wall00 URSTTrapGridBoxComponent
---@field Box_Collision UBoxComponent
---@field Collision USceneComponent
---@field Geometry USceneComponent
---@field TrapGrid USceneComponent
ABP_Archway_B_Merged_C = {}
