---@meta

---@class ABP_Arches_Resort_Bridge_A_C : ABP_OMDTrapGrid_C
---@field Cren_Stepped_Square_Group_CS2 UStaticMeshComponent
---@field Cren_Stepped_Square_Group_CS1 UStaticMeshComponent
---@field Archway_Wide_Resort_Stone_A_SM5 UStaticMeshComponent
---@field Archway_Wide_Resort_Stone_A_SM4 UStaticMeshComponent
---@field Archway_Wide_Resort_Stone_A_SM3 UStaticMeshComponent
---@field Wall07 URSTTrapGridBoxComponent
---@field Wall06 URSTTrapGridBoxComponent
---@field Wall05 URSTTrapGridBoxComponent
---@field Wall04 URSTTrapGridBoxComponent
---@field Wall03 URSTTrapGridBoxComponent
---@field Wall02 URSTTrapGridBoxComponent
---@field Wall01 URSTTrapGridBoxComponent
---@field Wall00 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Archway_Wide_Resort_Stone_A_SM2 UStaticMeshComponent
---@field Archway_Wide_Resort_Stone_A_SM UStaticMeshComponent
---@field Archway_Wide_Resort_Stone_A_SM1 UStaticMeshComponent
---@field Archway_2x05x2_StoneBlock3x_A2 UStaticMeshComponent
---@field Archway_2x05x2_StoneBlock3x_A1 UStaticMeshComponent
---@field Archway_2x05x2_StoneBlock3x_A UStaticMeshComponent
---@field Garden_Railing_EndCap_SM_Merged1 UStaticMeshComponent
---@field Cren_Stepped_Square_Group_CS UStaticMeshComponent
---@field Column_Square_Taper_1_4_StoneWall_SM1 UStaticMeshComponent
---@field Garden_Railing_EndCap_SM_Merged UStaticMeshComponent
---@field Column_Square_Taper_1_4_StoneWall_SM UStaticMeshComponent
---@field Archway_Resort_Stone_Endcap_A_SM1 UStaticMeshComponent
---@field Archway_Resort_Stone_Endcap_A_SM UStaticMeshComponent
---@field Geo USceneComponent
---@field Box_Collision1 UBoxComponent
---@field Box_Collision UBoxComponent
ABP_Arches_Resort_Bridge_A_C = {}
