---@meta

---@class ABP_Bridge_4x1_Wood_A_C : ABP_OMDTrapGrid_C
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field RSTTrapGridBox URSTTrapGridBoxComponent
---@field Wood_Log_300W_A2 UStaticMeshComponent
---@field Wood_Log_300W_A UStaticMeshComponent
---@field Wood_Log_300W_A1 UStaticMeshComponent
---@field Wood_Log_300W_A3 UStaticMeshComponent
---@field Wood_Log_300W_A4 UStaticMeshComponent
---@field Wood_Log_300W_A5 UStaticMeshComponent
---@field Rope_BendC1 UStaticMeshComponent
---@field Rope_BendC UStaticMeshComponent
---@field Wood_Grid_900C_A3 UStaticMeshComponent
---@field Wood_Grid_900C_A2 UStaticMeshComponent
---@field Wood_Grid_900C_A1 UStaticMeshComponent
---@field Wood_Grid_900C_A UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light5 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light4 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light3 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light2 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light1 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendK3 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendK2 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendK1 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendK UStaticMeshComponent
---@field BP_Dock_1x3_Straight_A_MERGED UStaticMeshComponent
---@field TrapGrid USceneComponent
---@field Geo USceneComponent
ABP_Bridge_4x1_Wood_A_C = {}
