---@meta

---@class ABP_BackAlley_Sewer_Ground_C_C : ABP_OMDTrapGrid_C
---@field Floor_4x4_CobbleStone_SM9 UStaticMeshComponent
---@field Floor_4x4_CobbleStone_SM12 UStaticMeshComponent
---@field Floor_1x3_CobbleStone_SM5 UStaticMeshComponent
---@field Floor_1x3_CobbleStone_SM6 UStaticMeshComponent
---@field Stair_1x2_Sewer_SM UStaticMeshComponent
---@field Stair_1x2_Sewer_SM1 UStaticMeshComponent
---@field Stair_1x2_Sewer_SM2 UStaticMeshComponent
---@field Floor_1x3_CobbleStone_SM3 UStaticMeshComponent
---@field Stair_5x2_Sewer_SM1 UStaticMeshComponent
---@field Floor_4x4_CobbleStone_SM13 UStaticMeshComponent
---@field Floor_1x4_CobbleStone_Color_SM UStaticMeshComponent
---@field Floor_1x4_CobbleStone_Color_SM1 UStaticMeshComponent
---@field Floor_4x4_CobbleStone_SM10 UStaticMeshComponent
---@field Floor_4x4_CobbleStone_SM11 UStaticMeshComponent
---@field Stair_1x2_Sewer_SM3 UStaticMeshComponent
---@field Stair_5x2_Sewer_SM UStaticMeshComponent
---@field RSTTrapGridBox9 URSTTrapGridBoxComponent
---@field RSTTrapGridBox8 URSTTrapGridBoxComponent
---@field RSTTrapGridBox7 URSTTrapGridBoxComponent
---@field Floor_3x4_V_CobbleStone_SM1 UStaticMeshComponent
---@field RSTTrapGridBox3 URSTTrapGridBoxComponent
---@field RSTTrapGridBox6 URSTTrapGridBoxComponent
---@field RSTTrapGridBox5 URSTTrapGridBoxComponent
---@field Floor_Tile_Straight_Sewer_SM7 UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM6 UStaticMeshComponent
---@field Floor_3x4_V_CobbleStone_SM UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM13 UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM12 UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM11 UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM10 UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM8 UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM3 UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM2 UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM9 UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM5 UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM4 UStaticMeshComponent
---@field Floor_Tile_Straight_Sewer_SM1 UStaticMeshComponent
---@field RSTTrapGridBox4 URSTTrapGridBoxComponent
---@field Floor_2x2_CobbleStone_SM24 UStaticMeshComponent
---@field RSTTrapGridBox2 URSTTrapGridBoxComponent
---@field RSTTrapGridBox URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Geo USceneComponent
ABP_BackAlley_Sewer_Ground_C_C = {}



