---@meta

---@class ABP_Building_Resort_B_C : ABP_OMDTrapGrid_C
---@field Wall_Resort_Adobe_Corner_2x2_B_SM1 UStaticMeshComponent
---@field Window_Pointed_3x_Trim3 UStaticMeshComponent
---@field Window_Pointed_3x_Trim2 UStaticMeshComponent
---@field Window_Pointed_3x_Trim1 UStaticMeshComponent
---@field Window_Pointed_3x_Trim UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM2 UStaticMeshComponent
---@field Floor_Resort_Stone_4x4_A_SM UStaticMeshComponent
---@field Roof_Terracotta_Corner_3x2_B_SM3 UStaticMeshComponent
---@field Roof_Terracotta_Corner_3x2_B_SM2 UStaticMeshComponent
---@field Roof_Terracotta_Corner_3x2_B_SM1 UStaticMeshComponent
---@field Roof_Terracotta_Corner_3x2_B_SM UStaticMeshComponent
---@field Crenel_TrimA_SM9 UStaticMeshComponent
---@field Crenel_TrimA_SM8 UStaticMeshComponent
---@field Crenel_TrimA_SM7 UStaticMeshComponent
---@field Crenel_TrimA_SM2 UStaticMeshComponent
---@field Crenel_TrimA_SM6 UStaticMeshComponent
---@field Crenel_TrimA_SM1 UStaticMeshComponent
---@field Trap_Wall3 URSTTrapGridBoxComponent
---@field Trap_Wall2 URSTTrapGridBoxComponent
---@field Trap_Wall1 URSTTrapGridBoxComponent
---@field Shutters_Resort_Wood_A_SM5 UStaticMeshComponent
---@field Window_Resort_Stone_A_SM5 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM4 UStaticMeshComponent
---@field Window_Resort_Stone_A_SM4 UStaticMeshComponent
---@field Wall_Resort_Adobe_2x2_B_SM UStaticMeshComponent
---@field Wall_Resort_Adobe_Corner_2x2_B_SM UStaticMeshComponent
---@field Wall_Window_Resort_Adobe_Corner_2x2_B_SM3 UStaticMeshComponent
---@field Wall_Window_Resort_Adobe_Corner_2x2_B_SM2 UStaticMeshComponent
---@field Wall_Resort_Adobe_Corner_1x2_B_SM2 UStaticMeshComponent
---@field Window_Resort_Wood_B_SM4 UStaticMeshComponent
---@field Window_Resort_Stone_A_SM15 UStaticMeshComponent
---@field Wall_Window_Resort_Adobe_Corner_2x2_B_SM UStaticMeshComponent
---@field Wall_Resort_Adobe_Corner_1x2_B_SM1 UStaticMeshComponent
---@field Window_Resort_Stone_Tall_B_SM UStaticMeshComponent
---@field Door_Resort_Wood_B_SM UStaticMeshComponent
---@field Wall_Door_Resort_Adobe_2x2_B_SM UStaticMeshComponent
---@field Wall_Resort_Adobe_Corner_1x2_B_SM UStaticMeshComponent
---@field Crenel_TrimA_SM3 UStaticMeshComponent
---@field Crenel_TrimA_SM UStaticMeshComponent
---@field Window_Resort_Wood_B_SM UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM6 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM UStaticMeshComponent
---@field Window_Resort_Stone_A_SM3 UStaticMeshComponent
---@field Window_Resort_Stone_A_SM2 UStaticMeshComponent
---@field Window_Resort_Stone_A_SM1 UStaticMeshComponent
---@field trap_wall URSTTrapGridBoxComponent
ABP_Building_Resort_B_C = {}



