---@meta

---@class ABP_BackAlley_Village_House_7x8_L_C : ABP_OMDTrapGrid_C
---@field Ceiling_4x4_Wood_A_SM UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union22'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union20'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union21'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union19'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union18'] UStaticMeshComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union11'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union12'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union17'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union16'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union15'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union14'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union12'] UStaticMeshComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union10'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union11'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union10'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union9'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union8'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union11'] UStaticMeshComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union9'] UStaticMeshComponent
---@field RSTTrapGridBox19 URSTTrapGridBoxComponent
---@field RSTTrapGridBox18 URSTTrapGridBoxComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union10'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union6'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union9'] UStaticMeshComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union8'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union11'] UStaticMeshComponent
---@field RSTTrapGridBox17 URSTTrapGridBoxComponent
---@field RSTTrapGridBox15 URSTTrapGridBoxComponent
---@field RSTTrapGridBox14 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Window_Wood10 UStaticMeshComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union9'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field BP USceneComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union5'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union4'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union3'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union2'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union'] UStaticMeshComponent
---@field Geo USceneComponent
ABP_BackAlley_Village_House_7x8_L_C = {}



