---@meta

---@class ABP_BackAlley_Brick_1Story_House_4x4_C : ABP_OMDTrapGrid_C
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field Ceiling_3x305_WoodLattice_SM_Union_2257BF6A UStaticMeshComponent
---@field Dead_Tree_1 UStaticMeshComponent
---@field Dead_Tree_3 UStaticMeshComponent
---@field Kiln_SM_Merged UStaticMeshComponent
---@field Floor_4x4_Wood_SM UStaticMeshComponent
---@field RSTTrapGridBox14 URSTTrapGridBoxComponent
---@field RSTTrapGridBox13 URSTTrapGridBoxComponent
---@field RSTTrapGridBox11 URSTTrapGridBoxComponent
---@field RSTTrapGridBox12 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union8'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union6'] UStaticMeshComponent
---@field BP USceneComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union5'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union3'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union1'] UStaticMeshComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union'] UStaticMeshComponent
---@field Geo USceneComponent
ABP_BackAlley_Brick_1Story_House_4x4_C = {}
