---@meta

---@class ABP_BackAlley_Village_2Story_House_4x4_A_C : ABP_OMDTrapGrid_C
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field RSTTrapGridBox30 URSTTrapGridBoxComponent
---@field RSTTrapGridBox29 URSTTrapGridBoxComponent
---@field RSTTrapGridBox19 URSTTrapGridBoxComponent
---@field RSTTrapGridBox28 URSTTrapGridBoxComponent
---@field RSTTrapGridBox27 URSTTrapGridBoxComponent
---@field RSTTrapGridBox26 URSTTrapGridBoxComponent
---@field RSTTrapGridBox25 URSTTrapGridBoxComponent
---@field RSTTrapGridBox24 URSTTrapGridBoxComponent
---@field RSTTrapGridBox23 URSTTrapGridBoxComponent
---@field RSTTrapGridBox22 URSTTrapGridBoxComponent
---@field RSTTrapGridBox21 URSTTrapGridBoxComponent
---@field RSTTrapGridBox20 URSTTrapGridBoxComponent
---@field Wall_Base_2x05_Wood_SM_Merge_ UStaticMeshComponent
---@field Floor_4x4_Wood_SM1 UStaticMeshComponent
---@field Floor_4x4_Wood_SM UStaticMeshComponent
---@field Ceiling_4x05_PlasterWood_SM_Cap_Union1 UStaticMeshComponent
---@field Ceiling_4x05_PlasterWood_SM_Cap_Union UStaticMeshComponent
---@field RSTTrapGridBox18 URSTTrapGridBoxComponent
---@field RSTTrapGridBox17 URSTTrapGridBoxComponent
---@field RSTTrapGridBox16 URSTTrapGridBoxComponent
---@field RSTTrapGridBox15 URSTTrapGridBoxComponent
---@field RSTTrapGridBox14 URSTTrapGridBoxComponent
---@field RSTTrapGridBox13 URSTTrapGridBoxComponent
---@field RSTTrapGridBox11 URSTTrapGridBoxComponent
---@field RSTTrapGridBox12 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Counter_Union5 UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union15'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union14'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union13'] UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Counter_Union4 UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Counter_Union2 UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Counter_Union UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union10'] UStaticMeshComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union8'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union6'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union8'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union6'] UStaticMeshComponent
---@field BP USceneComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union5'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union3'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union1'] UStaticMeshComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union'] UStaticMeshComponent
---@field Geo USceneComponent
ABP_BackAlley_Village_2Story_House_4x4_A_C = {}



