---@meta

---@class ABP_Bridge_4x1_Wood_C : ABP_OMDTrapGrid_C
---@field BP_Dock_1x3_Straight_A_B_Merged3 UStaticMeshComponent
---@field BP_Dock_1x3_Straight_A_B_Merged2 UStaticMeshComponent
---@field BP_Dock_1x3_Straight_A_B_Merged1 UStaticMeshComponent
---@field BP_Dock_1x3_Straight_A_B_Merged UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light5 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light4 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light3 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light2 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light1 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_CutEdges3 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_CutEdges2 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_CutEdges1 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_CutEdges UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendK3 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendK2 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendK1 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendK UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Union1 UStaticMeshComponent
---@field BP_Dock_1x3_Straight_A_MERGED UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Union UStaticMeshComponent
---@field RSTTrapGridBox2 URSTTrapGridBoxComponent
---@field RSTTrapGridBox1 URSTTrapGridBoxComponent
---@field RSTTrapGridBox URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Geo USceneComponent
ABP_Bridge_4x1_Wood_C = {}
