---@meta

---@class ABP_Building_Resort_B_C : ABP_OMDTrapGrid_C
---@field Building_Resort_Foundation_B_SM UStaticMeshComponent
---@field Trap_Wall1 URSTTrapGridBoxComponent
---@field Trap_Wall3 URSTTrapGridBoxComponent
---@field Trap_Wall2 URSTTrapGridBoxComponent
---@field trap_wall URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Shutters_Resort_Wood_A_SM UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM6 UStaticMeshComponent
---@field Window_Resort_Wood_B_SM UStaticMeshComponent
---@field Door_Resort_Wood_B_SM UStaticMeshComponent
---@field Window_Resort_Wood_B_SM4 UStaticMeshComponent
---@field Roof_Terracotta_Corner_3x2_B_SM1 UStaticMeshComponent
---@field Roof_Terracotta_Corner_3x2_B_SM3 UStaticMeshComponent
---@field Floor_Resort_Stone_4x4_A_SM UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM2 UStaticMeshComponent
---@field Roof_Terracotta_Corner_3x2_B_SM2 UStaticMeshComponent
---@field Roof_Terracotta_Corner_3x2_B_SM UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM4 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM5 UStaticMeshComponent
---@field Geo USceneComponent
ABP_Building_Resort_B_C = {}
