---@meta

---@class ABP_Bridge_4x1_Wood_C_C : ABP_OMDTrapGrid_C
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field Wall_05x15_Wood_SM_Union_1 UStaticMeshComponent
---@field Wall_05x15_Wood_SM_Union_ UStaticMeshComponent
---@field Ceiling_2x2_Wood_SM_Union1 UStaticMeshComponent
---@field Ceiling_2x2_Wood_SM_Union3 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light6 UStaticMeshComponent
---@field RSTTrapGridBox1 URSTTrapGridBoxComponent
---@field ['Dormer_B_1x3_ShingleC-Wood-White_SM_Union'] UStaticMeshComponent
---@field Ceiling_2x2_Wood_SM_Union2 UStaticMeshComponent
---@field Ceiling_2x2_Wood_SM_Union UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light5 UStaticMeshComponent
---@field RSTTrapGridBox URSTTrapGridBoxComponent
---@field Dormer_C_2x2_ShingleC_SM_Union UStaticMeshComponent
---@field Dormer_C_2x2_ShingleC_SM_Cap_Union1 UStaticMeshComponent
---@field Dormer_C_2x2_ShingleC_SM_Cap_Union UStaticMeshComponent
---@field BP_Dock_1x3_Straight_A_MERGED UStaticMeshComponent
---@field TrapGrid USceneComponent
---@field Geo USceneComponent
ABP_Bridge_4x1_Wood_C_C = {}
