---@meta

---@class ABP_BackAlley_Village_2Story_Base_3x5_B_C : ABP_OMDTrapGrid_C
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union9'] UStaticMeshComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union8'] UStaticMeshComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union6'] UStaticMeshComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union5'] UStaticMeshComponent
---@field Ceiling_4x05_PlasterWood_SM_Cap_Union1 UStaticMeshComponent
---@field Ceiling_4x05_PlasterWood_SM_Cap_Union UStaticMeshComponent
---@field Wood_Cantilever_Support2 UStaticMeshComponent
---@field Wood_Cantilever_Support1 UStaticMeshComponent
---@field Wood_Cantilever_Support UStaticMeshComponent
---@field Base_Column_Square_05_15_Stone_House_SM1 UStaticMeshComponent
---@field Base_Column_Square_05_15_Stone_House_SM UStaticMeshComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union4'] UStaticMeshComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union3'] UStaticMeshComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union2'] UStaticMeshComponent
---@field Floor_3x4_StoneFloor_SM1 UStaticMeshComponent
---@field Floor_3x4_StoneFloor_SM UStaticMeshComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union1'] UStaticMeshComponent
---@field Wall_3x15_WhiteBrick_SM_Window_Union_A2 UStaticMeshComponent
---@field Wall_3x15_WhiteBrick_SM_Window_Union_A8 UStaticMeshComponent
---@field Wall_3x15_WhiteBrick_SM_Window_Union_A7 UStaticMeshComponent
---@field Wall_3x15_WhiteBrick_SM_Window_Union_A5 UStaticMeshComponent
---@field Wall_3x15_WhiteBrick_SM_Window_Union_A3 UStaticMeshComponent
---@field Wall_3x15_WhiteBrick_SM_Window_Union_A1 UStaticMeshComponent
---@field ['Wall_2x1_WhiteBrick_SM_Union-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union2'] UStaticMeshComponent
---@field TrapGrid USceneComponent
---@field BP USceneComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union'] UStaticMeshComponent
---@field Geo USceneComponent
ABP_BackAlley_Village_2Story_Base_3x5_B_C = {}
