---@meta

---@class ABP_Building_Resort_D_C : ABP_OMDTrapGrid_C
---@field Trap_Wall5 URSTTrapGridBoxComponent
---@field Trap_Wall4 URSTTrapGridBoxComponent
---@field Wood_Deco_B3 UStaticMeshComponent
---@field Wood_Deco_B2 UStaticMeshComponent
---@field Wood_Deco_B1 UStaticMeshComponent
---@field Wood_Deco_B UStaticMeshComponent
---@field Building_Resort_Foundation_D_SM UStaticMeshComponent
---@field Trap_Wall3 URSTTrapGridBoxComponent
---@field trap_wall URSTTrapGridBoxComponent
---@field Trap_Wall1 URSTTrapGridBoxComponent
---@field Trap_Wall2 URSTTrapGridBoxComponent
---@field Window_Resort_Wood_B_SM4 UStaticMeshComponent
---@field Window_Resort_Wood_B_SM3 UStaticMeshComponent
---@field Window_Resort_Wood_B_SM UStaticMeshComponent
---@field Door_Resort_Wood_B_SM UStaticMeshComponent
---@field Wall_6x3_Whitewood_SM_Arc_Union UStaticMeshComponent
---@field Wall_6x3_Whitewood_SM_Arc_Union1 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM2 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM1 UStaticMeshComponent
---@field Roof_Resort_Terracotta_Curve_A_SM UStaticMeshComponent
---@field TrapGrid USceneComponent
---@field Geo USceneComponent
ABP_Building_Resort_D_C = {}
