---@meta

---@class ABP_Building_Resort_C_C : ABP_OMDTrapGrid_C
---@field Building_Resort_Foundation_C_SM UStaticMeshComponent
---@field trap_wall URSTTrapGridBoxComponent
---@field Trap_Wall6 URSTTrapGridBoxComponent
---@field Trap_Wall1 URSTTrapGridBoxComponent
---@field Trap_Wall3 URSTTrapGridBoxComponent
---@field Trap_Wall4 URSTTrapGridBoxComponent
---@field Trap_Wall5 URSTTrapGridBoxComponent
---@field Trap_Wall2 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Wood_Square_600W_A_Joint_Light UStaticMeshComponent
---@field Wood_Square_600W_A_Joint_Light3 UStaticMeshComponent
---@field Wood_Square_600W_A_Joint_Light2 UStaticMeshComponent
---@field Wood_Square_600W_A_Joint_Light1 UStaticMeshComponent
---@field Door_Resort_Wood_A_SM UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM7 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM5 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM6 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM8 UStaticMeshComponent
---@field Shutters_Resort_Wood_B_SM UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM2 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM1 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM9 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM11 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM10 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM4 UStaticMeshComponent
---@field Shutters_Resort_Wood_A_SM UStaticMeshComponent
---@field Roof_Terracotta_10x6_A_SM UStaticMeshComponent
---@field Geo USceneComponent
ABP_Building_Resort_C_C = {}
