---@meta

---@class ABP_BackAlley_Sewer_CeilingGroup_D_C : ABP_OMDTrapGrid_C
---@field Ceiling_ArchTileBig_T_4x7B_Sewer_SM UStaticMeshComponent
---@field Pipe_T_300x150_SM_Union UStaticMeshComponent
---@field Ceiling_ArchTileBig_Straight_2x4_Sewer_SM UStaticMeshComponent
---@field Pipe_X_300x300_SM_Union1 UStaticMeshComponent
---@field Pipe_Elbow_150x150_SM_Union UStaticMeshComponent
---@field Pipe_ValveA_SM UStaticMeshComponent
---@field Pipe_Elbow_150x150_SM_Union9 UStaticMeshComponent
---@field Pipe_300A_SM_Union5 UStaticMeshComponent
---@field Pipe_300A_SM_Union4 UStaticMeshComponent
---@field Pipe_300A_SM_Union3 UStaticMeshComponent
---@field Pipe_300A_SM_Union2 UStaticMeshComponent
---@field Pipe_Elbow_150x150_SM_Union2 UStaticMeshComponent
---@field Pipe_Elbow_150x150_SM_Union8 UStaticMeshComponent
---@field Pipe_Elbow_150x150_SM_Union7 UStaticMeshComponent
---@field Pipe_Elbow_150x150_SM_Union5 UStaticMeshComponent
---@field Pipe_Elbow_150x150_SM_Union4 UStaticMeshComponent
---@field Pipe_300A_SM_Union1 UStaticMeshComponent
---@field Pipe_T_300x150_SM_Union1 UStaticMeshComponent
---@field Pipe_900_SM_Union UStaticMeshComponent
---@field Pipe_300B_SM_Union UStaticMeshComponent
---@field Box1 UBoxComponent
---@field Box UBoxComponent
---@field TrapGrid USceneComponent
---@field Geo USceneComponent
ABP_BackAlley_Sewer_CeilingGroup_D_C = {}
