---@meta

---@class ABP_BackAlley_Village_1Story_House_3x5_A_Vista_C : ABP_OMDTrapGrid_C
---@field RSTTrapGridBox26 URSTTrapGridBoxComponent
---@field RSTTrapGridBox25 URSTTrapGridBoxComponent
---@field RSTTrapGridBox24 URSTTrapGridBoxComponent
---@field RSTTrapGridBox23 URSTTrapGridBoxComponent
---@field Crenel_BaseD_CastStone_SubD3 UStaticMeshComponent
---@field Crenel_BaseD_CastStone_SubD2 UStaticMeshComponent
---@field Crenel_BaseD_CastStone_SubD1 UStaticMeshComponent
---@field Crenel_BaseD_CastStone_Sub1B UStaticMeshComponent
---@field Crenel_BaseD_CastStone_Sub1B3 UStaticMeshComponent
---@field Crenel_BaseD_CastStone_Sub1B2 UStaticMeshComponent
---@field Crenel_BaseD_CastStone_Sub1B1 UStaticMeshComponent
---@field Crenel_BaseD_CastStone_SubD UStaticMeshComponent
---@field RSTTrapGridBox22 URSTTrapGridBoxComponent
---@field RSTTrapGridBox21 URSTTrapGridBoxComponent
---@field RSTTrapGridBox20 URSTTrapGridBoxComponent
---@field RSTTrapGridBox19 URSTTrapGridBoxComponent
---@field RSTTrapGridBox18 URSTTrapGridBoxComponent
---@field RSTTrapGridBox17 URSTTrapGridBoxComponent
---@field RSTTrapGridBox16 URSTTrapGridBoxComponent
---@field RSTTrapGridBox15 URSTTrapGridBoxComponent
---@field Floor_3x4_V_Wood_SM1 UStaticMeshComponent
---@field Floor_3x4_V_Wood_SM UStaticMeshComponent
---@field Ceiling_5x05_PlasterWood_SM_Union1 UStaticMeshComponent
---@field Ceiling_5x05_PlasterWood_SM_Union UStaticMeshComponent
---@field Ceiling_05x3_Wood_SM_A_Union1 UStaticMeshComponent
---@field Ceiling_05x3_Wood_SM_A_Union UStaticMeshComponent
---@field ['Base_Column_Square_05_15_Brick-Stone_SM3'] UStaticMeshComponent
---@field ['Base_Column_Square_05_15_Brick-Stone_SM2'] UStaticMeshComponent
---@field ['Base_Column_Square_05_15_Brick-Stone_SM1'] UStaticMeshComponent
---@field ['Base_Column_Square_05_15_Brick-Stone_SM'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union13'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union8'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union14'] UStaticMeshComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union6'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union12'] UStaticMeshComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union1'] UStaticMeshComponent
---@field ['Wall_2x1_WhiteBrick_SM_Union-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union2'] UStaticMeshComponent
---@field Wall_3x15_WhiteBrick_SM_Window_Union_A UStaticMeshComponent
---@field RSTTrapGridBox14 URSTTrapGridBoxComponent
---@field RSTTrapGridBox13 URSTTrapGridBoxComponent
---@field RSTTrapGridBox11 URSTTrapGridBoxComponent
---@field RSTTrapGridBox12 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field BP USceneComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union4'] UStaticMeshComponent
---@field Geo USceneComponent
ABP_BackAlley_Village_1Story_House_3x5_A_Vista_C = {}



