---@meta

---@class ABP_Crane_Fishmarket_Large_C : ABP_OMDTrapGrid_C
---@field Wood_Plank_300W_A15 UStaticMeshComponent
---@field Wood_Plank_300W_A14 UStaticMeshComponent
---@field Wood_Plank_300W_A13 UStaticMeshComponent
---@field Wood_Plank_300W_A12 UStaticMeshComponent
---@field Wood_Plank_300W_A11 UStaticMeshComponent
---@field Wood_Plank_300W_A10 UStaticMeshComponent
---@field Wood_Support_A5 UStaticMeshComponent
---@field Wood_Plank_300W_A9 UStaticMeshComponent
---@field Wood_Support_A2 UStaticMeshComponent
---@field Wood_Plank_300W_A8 UStaticMeshComponent
---@field Wood_Support_A1 UStaticMeshComponent
---@field Wood_Support_A UStaticMeshComponent
---@field Planter_Coastal_2x2x1_SM UStaticMeshComponent
---@field Wood_Plank_750W_A10 UStaticMeshComponent
---@field Wood_Plank_750W_A9 UStaticMeshComponent
---@field Wood_Plank_750W_A8 UStaticMeshComponent
---@field Wood_Plank_750W_A7 UStaticMeshComponent
---@field Wood_Plank_750W_A6 UStaticMeshComponent
---@field Wood_Plank_750W_A UStaticMeshComponent
---@field Wood_Plank_750W_A4 UStaticMeshComponent
---@field Wood_Plank_750W_A2 UStaticMeshComponent
---@field Wood_Plank_750W_A3 UStaticMeshComponent
---@field Wood_Plank_750W_A5 UStaticMeshComponent
---@field Wood_Plank_750W_A11 UStaticMeshComponent
---@field Wood_Plank_750W_A1 UStaticMeshComponent
---@field Wood_Plank_300W_A7 UStaticMeshComponent
---@field Wood_Plank_300W_A6 UStaticMeshComponent
---@field Wood_Plank_300W_A5 UStaticMeshComponent
---@field Wood_Square_300W_A3 UStaticMeshComponent
---@field Wood_Square_300W_A2 UStaticMeshComponent
---@field Wood_Square_300W_A1 UStaticMeshComponent
---@field Wood_Plank_300W_A4 UStaticMeshComponent
---@field Wood_Plank_300W_A1 UStaticMeshComponent
---@field Wood_Plank_300W_A UStaticMeshComponent
---@field Wood_Square_600W_A3 UStaticMeshComponent
---@field Wood_Square_600W_A2 UStaticMeshComponent
---@field Wood_Square_600W_A1 UStaticMeshComponent
---@field Wood_Square_600W_A UStaticMeshComponent
---@field Wood_Square_300W_A UStaticMeshComponent
---@field RSTTrapGridBox28 URSTTrapGridBoxComponent
---@field RSTTrapGridBox27 URSTTrapGridBoxComponent
---@field RSTTrapGridBox26 URSTTrapGridBoxComponent
---@field RSTTrapGridBox25 URSTTrapGridBoxComponent
---@field Collision USceneComponent
---@field Geo USceneComponent
---@field TrapGrid USceneComponent
ABP_Crane_Fishmarket_Large_C = {}



