---@meta

---@class ABP_Courtyard_4x3_ElevatedDeck_A_C : ABP_OMDTrapGrid_C
---@field Roof_Terracotta_3x2_B_SM3 UStaticMeshComponent
---@field Roof_Terracotta_3x2_B_SM2 UStaticMeshComponent
---@field DryDocks_Platform_4x2_Walkway_SM2 UStaticMeshComponent
---@field DryDocks_Platform_4x2_Walkway_SM1 UStaticMeshComponent
---@field Roof_Terracotta_3x2_B_SM4 UStaticMeshComponent
---@field Roof_Terracotta_3x2_B_SM1 UStaticMeshComponent
---@field Roof_Terracotta_Corner_3x2_B_SM1 UStaticMeshComponent
---@field Roof_Terracotta_Corner_3x2_B_SM UStaticMeshComponent
---@field Roof_Terracotta_3x2_B_SM UStaticMeshComponent
---@field RSTTrapGridBox14 URSTTrapGridBoxComponent
---@field RSTTrapGridBox13 URSTTrapGridBoxComponent
---@field RSTTrapGridBox12 URSTTrapGridBoxComponent
---@field RSTTrapGridBox11 URSTTrapGridBoxComponent
---@field DryDocks_Platform_4x2_Walkway_SM UStaticMeshComponent
---@field RSTTrapGridBox10 URSTTrapGridBoxComponent
---@field Props USceneComponent
---@field RSTTrapGridBox9 URSTTrapGridBoxComponent
---@field Geo USceneComponent
---@field TrapGrid USceneComponent
---@field Collision USceneComponent
ABP_Courtyard_4x3_ElevatedDeck_A_C = {}
