---@meta

---@class ABP_CastlePlaza_Village_House_4x4_A_C : ABP_OMDTrapGrid_C
---@field RSTTrapGridBox17 URSTTrapGridBoxComponent
---@field RSTTrapGridBox16 URSTTrapGridBoxComponent
---@field RSTTrapGridBox15 URSTTrapGridBoxComponent
---@field RSTTrapGridBox14 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field ['Chimney_C_ExposedBrick_Concrete_SM-Wood-White_SM_UnionWood_Window_SM_Union12'] UStaticMeshComponent
---@field Window_Wood9 UStaticMeshComponent
---@field Window_Wood8 UStaticMeshComponent
---@field Window_Wood7 UStaticMeshComponent
---@field Window_Wood6 UStaticMeshComponent
---@field Window_Wood5 UStaticMeshComponent
---@field Window_Wood4 UStaticMeshComponent
---@field Window_Wood1 UStaticMeshComponent
---@field Window_Wood UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union11'] UStaticMeshComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union8'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union6'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union9'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union8'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union6'] UStaticMeshComponent
---@field BP_Wood_Pillar_Support_600W_A_COrner3 UChildActorComponent
---@field BP_Wood_Pillar_Support_600W_A_COrner2 UChildActorComponent
---@field BP_Wood_Pillar_Support_600W_A_COrner1 UChildActorComponent
---@field BP_Wood_Pillar_Support_600W_A_Corner UChildActorComponent
---@field BP USceneComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union5'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union3'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union1'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union'] UStaticMeshComponent
---@field Geo USceneComponent
ABP_CastlePlaza_Village_House_4x4_A_C = {}
