---@meta

---@class ABP_Ceiling_BackAlley_Sewer_MainB1_C : ABP_OMDTrapGrid_C
---@field RSTTrapGridBox16 URSTTrapGridBoxComponent
---@field RSTTrapGridBox15 URSTTrapGridBoxComponent
---@field RSTTrapGridBox14 URSTTrapGridBoxComponent
---@field RSTTrapGridBox13 URSTTrapGridBoxComponent
---@field RSTTrapGridBox12 URSTTrapGridBoxComponent
---@field Ceiling_2x2_Sewer_A_SM5 UStaticMeshComponent
---@field Ceiling_2x2_Sewer_A_SM4 UStaticMeshComponent
---@field Ceiling_2x2_Sewer_A_SM1 UStaticMeshComponent
---@field Ceiling_2x2_Sewer_A_SM UStaticMeshComponent
---@field Arch_1x1x4_Sewer_SM1 UStaticMeshComponent
---@field Arch_1x1x4_Sewer_SM UStaticMeshComponent
---@field Ceiling_4x4_Sewer_A_SM31 UStaticMeshComponent
---@field Ceiling_4x4_Sewer_A_SM30 UStaticMeshComponent
---@field Ceiling_4x4_Sewer_A_SM25 UStaticMeshComponent
---@field Ceiling_4x4_Sewer_A_SM24 UStaticMeshComponent
---@field RSTTrapGridBox11 URSTTrapGridBoxComponent
---@field RSTTrapGridBox10 URSTTrapGridBoxComponent
---@field RSTTrapGridBox9 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Ceiling_2x2_Sewer_A_SM3 UStaticMeshComponent
---@field Ceiling_Hole_2x2_Sewer_SM1 UStaticMeshComponent
---@field Ceiling_Hole_2x2_Sewer_SM UStaticMeshComponent
---@field Ceiling_2x2_Sewer_A_SM2 UStaticMeshComponent
---@field Ceiling_4x4_Sewer_A_SM23 UStaticMeshComponent
---@field Ceiling_4x4_Sewer_A_SM28 UStaticMeshComponent
---@field Ceiling_4x4_Sewer_A_SM2 UStaticMeshComponent
---@field Ceiling_4x4_Sewer_A_SM26 UStaticMeshComponent
---@field Geo USceneComponent
ABP_Ceiling_BackAlley_Sewer_MainB1_C = {}
