---@meta

---@class ABP_CastlePlaza_Waterworks_Vista_Wall_C_C : ABP_OMDTrapGrid_C
---@field Archway_Wall_Top_SM1 UStaticMeshComponent
---@field ['Crenellation_Pointed_4x _SM1'] UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM22 UStaticMeshComponent
---@field Archway_Wall_Top_SM UStaticMeshComponent
---@field Arch_1x05x4_StoneWall_SM3 UStaticMeshComponent
---@field Arch_1x05x4_StoneWall_SM2 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM21 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM20 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM19 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM17 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM14 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM18 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM15 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM16 UStaticMeshComponent
---@field Arch_1x05x4_StoneWall_SM UStaticMeshComponent
---@field ['Crenellation_Pointed_4x _SM'] UStaticMeshComponent
---@field ArchWall_4x2_StoneWall_SM UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM10 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM6 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM13 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM8 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM5 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM4 UStaticMeshComponent
---@field Crenellation_Double_RB5 UStaticMeshComponent
---@field Crenellation_Double_RB4 UStaticMeshComponent
---@field Window_Roof_SeaBlue_SM4 UStaticMeshComponent
---@field Window_Roof_SeaBlue_SM1 UStaticMeshComponent
---@field Window_Roof_SeaBlue_SM3 UStaticMeshComponent
---@field Window_Roof_SeaBlue_SM UStaticMeshComponent
---@field Cren_Corner_RB3 UStaticMeshComponent
---@field Cren_Corner_RB2 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM7 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM3 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM12 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM12 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM10 UStaticMeshComponent
---@field Crenellation_Double_RB3 UStaticMeshComponent
---@field Crenellation_Double_RB2 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM9 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM1 UStaticMeshComponent
---@field Cren_Corner_RB1 UStaticMeshComponent
---@field Cren_Corner_RB UStaticMeshComponent
---@field Crenellation_Double_RB1 UStaticMeshComponent
---@field Crenellation_Double_RB UStaticMeshComponent
---@field Arch_1x05x4_StoneWall_SM1 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM2 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM UStaticMeshComponent
---@field Geometry USceneComponent
ABP_CastlePlaza_Waterworks_Vista_Wall_C_C = {}
