---@meta

---@class ABP_CastlePlaza_Waterworks_Vista_Wall_A_C : ABP_OMDTrapGrid_C
---@field Crenellation_Coastal_5x_SM3 UStaticMeshComponent
---@field Crenellation_Coastal_5x_SM2 UStaticMeshComponent
---@field Crenellation_Coastal_5x_SM1 UStaticMeshComponent
---@field Crenellation_Coastal_5x_SM UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM15 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM12 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM9 UStaticMeshComponent
---@field Crenellation_Double_RB5 UStaticMeshComponent
---@field Crenellation_Double_RB4 UStaticMeshComponent
---@field ColumnTrim_CastStone_1800W3 UStaticMeshComponent
---@field Arch_1x05x4_StoneWall_SM5 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM16 UStaticMeshComponent
---@field Arch_1x05x4_StoneWall_SM4 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM14 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM10 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM14 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM8 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM13 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM12 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM13 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM11 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM10 UStaticMeshComponent
---@field ColumnTrim_CastStone_1800W2 UStaticMeshComponent
---@field ColumnTrim_CastStone_1800W1 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM11 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM9 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM5 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM4 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM1 UStaticMeshComponent
---@field ColumnTrim_CastStone_1800W UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM8 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM7 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM6 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM5 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM4 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM3 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM1 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM UStaticMeshComponent
---@field Arch_1x05x4_StoneWall_SM3 UStaticMeshComponent
---@field Arch_1x05x4_StoneWall_SM UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM7 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM6 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM3 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM2 UStaticMeshComponent
---@field Wall_StoneWall_Castle_4x2_SM UStaticMeshComponent
---@field Box_Collision UBoxComponent
---@field Collision USceneComponent
---@field Geometry USceneComponent
ABP_CastlePlaza_Waterworks_Vista_Wall_A_C = {}



