---@meta

---@class ABP_Courtyard_Stewpot_C : ABP_OMDTrapGrid_C
---@field Orc_Archer_GIB_Pelvis_SM1 UStaticMeshComponent
---@field Orc_Archer_GIB_Head_SM UStaticMeshComponent
---@field Orc_Archer_GIB_Calf_L_SM1 UStaticMeshComponent
---@field Orc_Archer_GIB_Lowerarm_L_SM UStaticMeshComponent
---@field Orc_Archer_GIB_Calf_L_SM UStaticMeshComponent
---@field P_Oven_Steam1 UParticleSystemComponent
---@field NS_Cauldron_Large UNiagaraComponent
---@field SM_Courtyard_Stewpot_Potion_01 UStaticMeshComponent
---@field SM_Courtyard_Stewpot_01 UStaticMeshComponent
---@field Chain_Short_x10 UStaticMeshComponent
---@field Chain_Short_x9 UStaticMeshComponent
---@field Chain_Short_x8 UStaticMeshComponent
---@field Chain_Short_x7 UStaticMeshComponent
---@field Chain_Short_x6 UStaticMeshComponent
---@field SM_Courtyard_Stewpot_Spoon_01 UStaticMeshComponent
---@field SM_Courtyard_Stewpot_Base_01 UStaticMeshComponent
---@field Chain_Ring_End3 UStaticMeshComponent
---@field Chain_Ring_End2 UStaticMeshComponent
---@field Chain_Ring_End1 UStaticMeshComponent
---@field Chain_Ring_End UStaticMeshComponent
ABP_Courtyard_Stewpot_C = {}
