---@meta

---@class ABP_CastlePlaza_Vista_Wall_Tower_A_C : ABP_OMDTrapGrid_C
---@field Roof_Tiled_x2_Base3 UStaticMeshComponent
---@field Roof_Tiled_x2_Base2 UStaticMeshComponent
---@field Roof_Tiled_x2_Base1 UStaticMeshComponent
---@field Roof_Tiled_x2_Base UStaticMeshComponent
---@field Crenellation_Pointed_Merlon_SM3 UStaticMeshComponent
---@field Crenellation_Pointed_Merlon_SM2 UStaticMeshComponent
---@field Column_Square_Taper_1_4_StoneWall_SM3 UStaticMeshComponent
---@field Column_Square_Taper_1_4_StoneWall_SM2 UStaticMeshComponent
---@field Cren_Top_Octogon UStaticMeshComponent
---@field Crenellation_Pointed_Merlon_SM1 UStaticMeshComponent
---@field Cren_Bottom_Octogon2 UStaticMeshComponent
---@field Crenellation_Pointed_Merlon_SM UStaticMeshComponent
---@field Column_Square_Taper_1_4_StoneWall_SM1 UStaticMeshComponent
---@field Cren_Bottom_Octogon UStaticMeshComponent
---@field Column_OctoTaper_2x2_StoneWall_SM1 UStaticMeshComponent
---@field Column_OctoTaper_2x4_StoneWall_SM UStaticMeshComponent
---@field Column_Square_Taper_1_4_StoneWall_SM UStaticMeshComponent
---@field Column_OctoTaper_2x2_StoneWall_SM UStaticMeshComponent
---@field Geometry USceneComponent
ABP_CastlePlaza_Vista_Wall_Tower_A_C = {}
