---@meta

---@class ABP_Courtyard_Shed_4x2_A_C : ABP_OMDTrapGrid_C
---@field WoodPlank_4x1_Floor_A UStaticMeshComponent
---@field Wall_Tile_Stucco_2x2_A_SM1 UStaticMeshComponent
---@field Wall_Tile_Stucco_2x2_A_SM UStaticMeshComponent
---@field Wall_Angle_2x1_Stucco_A_SM2 UStaticMeshComponent
---@field Roof_Terracotta_3x2_A_SM UStaticMeshComponent
---@field Wood_Square_1200W_A_Light_NoTaper_BendN8 UStaticMeshComponent
---@field Wood_Square_1200W_A_Light_NoTaper_BendN7 UStaticMeshComponent
---@field Wood_Square_1200W_A_Light_NoTaper_BendN6 UStaticMeshComponent
---@field Wood_Square_1200W_A_Light_NoTaper_BendN5 UStaticMeshComponent
---@field Wall_Angle_2x1_Stucco_A_SM UStaticMeshComponent
---@field Wood_Support_A5 UStaticMeshComponent
---@field Wood_Support_A4 UStaticMeshComponent
---@field Wood_Support_A UStaticMeshComponent
---@field Wood_Support_A1 UStaticMeshComponent
---@field Wood_Support_A2 UStaticMeshComponent
---@field Wood_Support_A3 UStaticMeshComponent
---@field Wood_Square_1200W_A_Light_NoTaper_BendN4 UStaticMeshComponent
---@field Trap_Wall3 URSTTrapGridBoxComponent
---@field Trap_Wall2 URSTTrapGridBoxComponent
---@field Wood_Square_1200W_A_Light_NoTaper_BendN3 UStaticMeshComponent
---@field Wall_Bottom_Stucco_2x2_A_SM1 UStaticMeshComponent
---@field Wood_Square_1200W_A_Light_NoTaper_BendN2 UStaticMeshComponent
---@field Wall_Bottom_Stucco_2x2_A_SM UStaticMeshComponent
---@field Wood_Square_1200W_A_Light_NoTaper_BendN1 UStaticMeshComponent
---@field Wood_Square_1200W_A_Light_NoTaper_BendN UStaticMeshComponent
---@field Wall_Bottom_Stone_Castle_Courtyard_4x2_C_SM UStaticMeshComponent
---@field trap_wall URSTTrapGridBoxComponent
ABP_Courtyard_Shed_4x2_A_C = {}
