---@meta

---@class ABP_CastlePlaza_Village_2Story_House_4x6_A_Vista_C : ABP_OMDTrapGrid_C
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field Wood_Window_N1 UStaticMeshComponent
---@field Wood_Window_N UStaticMeshComponent
---@field Window_Wood9 UStaticMeshComponent
---@field Window_Wood8 UStaticMeshComponent
---@field Window_Wood7 UStaticMeshComponent
---@field Window_Wood6 UStaticMeshComponent
---@field Window_Wood5 UStaticMeshComponent
---@field Window_Wood4 UStaticMeshComponent
---@field Window_Wood3 UStaticMeshComponent
---@field Window_Wood2 UStaticMeshComponent
---@field Window_Wood1 UStaticMeshComponent
---@field Window_Wood UStaticMeshComponent
---@field RSTTrapGridBox14 URSTTrapGridBoxComponent
---@field RSTTrapGridBox13 URSTTrapGridBoxComponent
---@field RSTTrapGridBox11 URSTTrapGridBoxComponent
---@field RSTTrapGridBox12 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Wood_Door_B_Light1 UStaticMeshComponent
---@field Wood_Door_B_Light UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Counter_Union5 UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union15'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union14'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union11'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union13'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union12'] UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Counter_Union4 UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Counter_Union3 UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Counter_Union2 UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Counter_Union1 UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Counter_Union UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_UnionDormer_B_1x3_Blue-Wood-White_SM_UnionWood_Window_SM_Union10'] UStaticMeshComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union8'] UStaticMeshComponent
---@field ['Roof_4x3x3_Blue_SM_End_Union-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Gable_5x4_A_WhiteBrick_SM_Merge-Wood_Window_SM_Union6'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union9'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union8'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union7'] UStaticMeshComponent
---@field ['Wall_3x05_Wood_SM_Cut_Union-Wood_Window_SM_Union6'] UStaticMeshComponent
---@field BP_Wood_Pillar_Support_600W_A_COrner3 UChildActorComponent
---@field BP_Wood_Pillar_Support_600W_A_COrner2 UChildActorComponent
---@field BP_Wood_Pillar_Support_600W_A_COrner1 UChildActorComponent
---@field BP_Wood_Pillar_Support_600W_A_Corner UChildActorComponent
---@field BP USceneComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union5'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union4'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union3'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union2'] UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_Window_SM_Union1'] UStaticMeshComponent
---@field ['Wall_4x2_Wainscot_White-Brick-Seablue_SM_Door-Window_Union_-Wood_Window_SM_Union'] UStaticMeshComponent
---@field Geo USceneComponent
ABP_CastlePlaza_Village_2Story_House_4x6_A_Vista_C = {}



