---@meta

---@class ABP_Dome_D_Full_A_Group_C : AActor
---@field Proto_Dome_D_FrontFace9 UStaticMeshComponent
---@field Proto_Dome_D_FrontFace8 UStaticMeshComponent
---@field Proto_Dome_D_FrontFace7 UStaticMeshComponent
---@field Proto_Dome_D_FrontFace6 UStaticMeshComponent
---@field Proto_Dome_D_FrontFace5 UStaticMeshComponent
---@field Proto_Dome_D_FrontFace4 UStaticMeshComponent
---@field Proto_Dome_D_Tile_FrontFace_Glass1 UStaticMeshComponent
---@field Proto_Dome_D_FrontFace2 UStaticMeshComponent
---@field Proto_Dome_RiftRoom_C_Window UStaticMeshComponent
---@field Proto_Dome_RiftRoom_C_Window_Glass UStaticMeshComponent
---@field Proto_Dome_D_Tile_FrontFace_Glass UStaticMeshComponent
---@field Proto_Dome_D_Glass4 UStaticMeshComponent
---@field Proto_Dome_D_Tile4 UStaticMeshComponent
---@field Proto_Dome_D_Glass UStaticMeshComponent
---@field Proto_Dome_D_Glass6 UStaticMeshComponent
---@field Proto_Dome_D_Glass8 UStaticMeshComponent
---@field Proto_Dome_D_Glass1 UStaticMeshComponent
---@field Proto_Dome_D_Glass10 UStaticMeshComponent
---@field Proto_Dome_D_Tile10 UStaticMeshComponent
---@field Proto_Dome_D_Tile8 UStaticMeshComponent
---@field Proto_Dome_D_Tile6 UStaticMeshComponent
---@field Proto_Dome_D_Tile1 UStaticMeshComponent
---@field Proto_Dome_D_FrontFace UStaticMeshComponent
---@field Proto_Dome_D_Tile UStaticMeshComponent
---@field DefaultSceneRoot USceneComponent
ABP_Dome_D_Full_A_Group_C = {}
