---@meta

---@class ABP_DryDocks_ShopA_4x4_Gate_C : ABP_OMDTrapGrid_C
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field RSTTrapGridBox1 URSTTrapGridBoxComponent
---@field RSTTrapGridBox URSTTrapGridBoxComponent
---@field Gate_Gardens_RodIron_C5 UStaticMeshComponent
---@field Gate_Gardens_RodIron_C4 UStaticMeshComponent
---@field Dormer_E_15x2_Blue_SM_Union_1 UStaticMeshComponent
---@field Dormer_E_15x2_Blue_SM_Union_ UStaticMeshComponent
---@field Archway_2x05x2_Stone10 UStaticMeshComponent
---@field Archway_2x05x2_Stone9 UStaticMeshComponent
---@field Archway_2x05x2_Stone8 UStaticMeshComponent
---@field Archway_2x05x2_Stone7 UStaticMeshComponent
---@field Archway_2x05x2_Stone4 UStaticMeshComponent
---@field Gate_Gardens_RodIron_C3 UStaticMeshComponent
---@field Archway_2x05x2_Stone1 UStaticMeshComponent
---@field Props USceneComponent
---@field Tech USceneComponent
---@field Geo USceneComponent
---@field TrapGrid USceneComponent
---@field Collision USceneComponent
ABP_DryDocks_ShopA_4x4_Gate_C = {}
