---@meta

---@class ABP_DisplayCase_6x10_C_C : ABP_OMDTrapGrid_C
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field BP_Mountain_Weapon_Breakable UChildActorComponent
---@field BP_Gnoll_Dagger_GeoCol_Breakable UChildActorComponent
---@field BP_Skeleton_Cyclops_Clavicle_L_Breakable UChildActorComponent
---@field BP_FireFiend_ShinRight_Breakable UChildActorComponent
---@field BP_FireFiend_Left_Breakable1 UChildActorComponent
---@field BP_Skeleton_Cyclops_LowerArm_Breakable UChildActorComponent
---@field BP_FireFiend_Medium16_Breakable UChildActorComponent
---@field BP_FireFiend_Medium15_Breakable UChildActorComponent
---@field BP_FireFiend_Medium13_Breakable UChildActorComponent
---@field BP_FireFiend_Left_Breakable UChildActorComponent
---@field BP_Skeleton_FireFiend_Mage_SM4_Breakable UChildActorComponent
---@field BP_FireFiend_Weapon_Breakable UChildActorComponent
---@field BP_Skeleton_FireFiend_Mage_SM4_Breakable1 UChildActorComponent
---@field BP_Skeleton_Cyclops_Heavy_Axe_Breakable UChildActorComponent
---@field BP_Skeleton_FireFiend_Mage_Weapon_Breakable UChildActorComponent
---@field Wood_BookShelves_Shelve_600C_03 UStaticMeshComponent
---@field Wood_BookShelves_Shelve_600C_02 UStaticMeshComponent
---@field BP_Skeleton_Cyclops_Heavy_Attack_Nested_Breakable UChildActorComponent
---@field BP_Skeleton_FireFiend_Mage_Nested_Breakable1 UChildActorComponent
---@field BP_Skeleton_Cyclops_Druid_Nested_Breakable UChildActorComponent
---@field BP_Skeleton_FireFiend_Mage_Nested_Breakable UChildActorComponent
---@field BP_Orc_Glyph_Standing UChildActorComponent
---@field Orc_ArchWay_SM1 UStaticMeshComponent
---@field Orc_ArchWay_SM UStaticMeshComponent
---@field BP_Skeleton_Gnoll_Assassin_Attack_Nested_Breakable UChildActorComponent
---@field BP_Skeleton_Orc_Medium_Idle_Nested_Breakable UChildActorComponent
---@field Props USceneComponent
---@field DisplayCase_WoodFloor_2x8_SM UStaticMeshComponent
---@field Column_BaseC_CastStone UStaticMeshComponent
---@field Column_Square_1_2_StoneWall_SM UStaticMeshComponent
---@field Wall_Bottom_2x05_StoneWalls_SM UStaticMeshComponent
---@field Wall_Bottom_4x05_StoneWall_SM UStaticMeshComponent
---@field Column_Square_1_2_StoneWall_SM5 UStaticMeshComponent
---@field Column_Square_1_2_StoneWall_SM4 UStaticMeshComponent
---@field Column_BaseC_CastStone3 UStaticMeshComponent
---@field Column_BaseC_CastStone2 UStaticMeshComponent
---@field Column_Square_1_2_StoneWall_SM6 UStaticMeshComponent
---@field Column_BaseC_CastStone1 UStaticMeshComponent
---@field Wall_Bottom_4x05_StoneWall_SM1 UStaticMeshComponent
---@field Wall_Bottom_2x05_StoneWalls_SM1 UStaticMeshComponent
---@field DisplayCase_WoodFloor_2x8_SM1 UStaticMeshComponent
---@field Geo USceneComponent
---@field RSTTrapGridBox12 URSTTrapGridBoxComponent
---@field RSTTrapGridBox2 URSTTrapGridBoxComponent
---@field RSTTrapGridBox3 URSTTrapGridBoxComponent
---@field RSTTrapGridBox URSTTrapGridBoxComponent
---@field RSTTrapGridBox1 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field BP USceneComponent
ABP_DisplayCase_6x10_C_C = {}



