---@meta

---@class ABP_DryDocks_shop_B_C : ABP_OMDTrapGrid_C
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field Vendor_Stall_Awning_B_SubFrame_SM1 UStaticMeshComponent
---@field Vendor_Stall_Awning_B_Fabric_SM1 UStaticMeshComponent
---@field Vendor_Stall_Awning_B_Fabric_SM UStaticMeshComponent
---@field Vendor_Stall_Awning_B_SubFrame_SM UStaticMeshComponent
---@field Wall_4x05_Wood_SM2 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light8 UStaticMeshComponent
---@field RSTTrapGridBox9 URSTTrapGridBoxComponent
---@field Wall_2x05_Counter_ExposedBrick_SM_Union_3 UStaticMeshComponent
---@field Wood_Window_B3 UStaticMeshComponent
---@field Wall_2x05_Counter_ExposedBrick_SM_Union_2 UStaticMeshComponent
---@field WoodPlank_4x4_Floor_A1 UStaticMeshComponent
---@field Wall_3x2_WhiteBrick_SM_Union_1 UStaticMeshComponent
---@field RSTTrapGridBox8 URSTTrapGridBoxComponent
---@field Wood_Plank_600W_A_Light5 UStaticMeshComponent
---@field Wood_Support_A3 UStaticMeshComponent
---@field Wood_Window_G_Light_Shutter_Left7 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light4 UStaticMeshComponent
---@field Wall_2x05_Counter_ExposedBrick_SM_Union_1 UStaticMeshComponent
---@field Wood_Support_A2 UStaticMeshComponent
---@field Wood_Support_A UStaticMeshComponent
---@field Wood_Window_G_Light_Shutter_Left3 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light3 UStaticMeshComponent
---@field Wall_3x2_WhiteBrick_SM_Union_ UStaticMeshComponent
---@field Wood_Window_B1 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light1 UStaticMeshComponent
---@field Ceiling_4x4_Wood_A_SM UStaticMeshComponent
---@field WoodPlank_4x4_Floor_A UStaticMeshComponent
---@field RSTTrapGridBox7 URSTTrapGridBoxComponent
---@field Props USceneComponent
---@field TrapGrid USceneComponent
---@field Geo USceneComponent
ABP_DryDocks_shop_B_C = {}
