---@meta

---@class ABP_Drydocks_WoodDock_C : ABP_OMDTrapGrid_C
---@field Capsule6 UCapsuleComponent
---@field Capsule5 UCapsuleComponent
---@field Capsule4 UCapsuleComponent
---@field Capsule3 UCapsuleComponent
---@field Capsule2 UCapsuleComponent
---@field Capsule1 UCapsuleComponent
---@field Capsule UCapsuleComponent
---@field Wood_Log_1200W_A7 UStaticMeshComponent
---@field Wood_Log_1200W_A6 UStaticMeshComponent
---@field Wood_Log_1200W_A4 UStaticMeshComponent
---@field BP_Dock_2x2_Straight_D_Merged2 UStaticMeshComponent
---@field BP_Dock_2x2_Straight_D_Merged1 UStaticMeshComponent
---@field Wood_Log_1200W_A3 UStaticMeshComponent
---@field Wood_Log_1200W_A2 UStaticMeshComponent
---@field Wood_Log_1200W_A1 UStaticMeshComponent
---@field Wood_Log_1200W_A UStaticMeshComponent
---@field BP_Dock_2x2_Straight_D_MERGED UStaticMeshComponent
---@field Floor00 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Box UBoxComponent
---@field Collision USceneComponent
---@field StaticMesh USceneComponent
---@field SharedRoot USceneComponent
ABP_Drydocks_WoodDock_C = {}
