---@meta

---@class ABP_FishMarket_Bridge_B_C : ABP_OMDTrapGrid_C
---@field Proto_Crenellation_Coastal_SM3 UStaticMeshComponent
---@field Proto_Crenellation_Coastal_SM2 UStaticMeshComponent
---@field Proto_Crenellation_Coastal_SM1 UStaticMeshComponent
---@field Proto_Crenellation_Coastal_SM UStaticMeshComponent
---@field ArchWall_4x2_StoneWall_SM1 UStaticMeshComponent
---@field WoodPlank_2x2_Floor_A5 UStaticMeshComponent
---@field ArchWall_4x2_StoneWall_SM UStaticMeshComponent
---@field RSTTrapGridBox10 URSTTrapGridBoxComponent
---@field WoodPlank_2x2_Floor_A3 UStaticMeshComponent
---@field WoodPlank_2x2_Floor_A2 UStaticMeshComponent
---@field WoodPlank_2x2_Floor_A1 UStaticMeshComponent
---@field WoodPlank_2x2_Floor_A UStaticMeshComponent
---@field RSTTrapGridBox9 URSTTrapGridBoxComponent
---@field Wood_Plank_900W_A_Light UStaticMeshComponent
---@field Wood_Plank_900W_A_Light4 UStaticMeshComponent
---@field Wood_Plank_900W_A_Light2 UStaticMeshComponent
---@field Wood_Plank_900W_A_Light6 UStaticMeshComponent
---@field Wood_Plank_900W_A_Light1 UStaticMeshComponent
---@field Wood_Plank_900W_A_Light5 UStaticMeshComponent
---@field Wood_Plank_900W_A_Light3 UStaticMeshComponent
---@field RSTTrapGridBox8 URSTTrapGridBoxComponent
---@field RSTTrapGridBox7 URSTTrapGridBoxComponent
---@field Collision USceneComponent
---@field TrapGrid USceneComponent
---@field Geo USceneComponent
ABP_FishMarket_Bridge_B_C = {}
