---@meta

---@class ABP_FishMarket_UpTownShop_C_C : ABP_OMDTrapGrid_C
---@field BP_Dock_FishSign_A_Breakable UChildActorComponent
---@field SpotLight USpotLightComponent
---@field Wall_4x05_Wood_SM1 UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_SM_Merged1'] UStaticMeshComponent
---@field Wood_Window_G_Light_Shutter_Left1 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light2 UStaticMeshComponent
---@field Wood_Window_B1 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light1 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light UStaticMeshComponent
---@field Wood_Window_B UStaticMeshComponent
---@field Wood_Window_G_Light_Shutter_Left UStaticMeshComponent
---@field Wall_2x05_Counter_ExposedBrick_SM_Union_ UStaticMeshComponent
---@field Ceiling_4x4_Wood_A_SM UStaticMeshComponent
---@field Wall_4x05_Wood_SM UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_SM_Merged'] UStaticMeshComponent
---@field WoodPlank_4x4_Floor_A UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Union__ UStaticMeshComponent
---@field RSTTrapGridBox7 URSTTrapGridBoxComponent
---@field BP USceneComponent
---@field Props USceneComponent
---@field TrapGrid USceneComponent
---@field Collision USceneComponent
---@field Geo USceneComponent
ABP_FishMarket_UpTownShop_C_C = {}
