---@meta

---@class ABP_FishMarket_UpTownShop_A_C : ABP_OMDTrapGrid_C
---@field BP_Dock_FishSign_A_Breakable UChildActorComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Union__1 UStaticMeshComponent
---@field Ceiling_4x4_Wood_A_SM UStaticMeshComponent
---@field Wall_4x05_Wood_SM UStaticMeshComponent
---@field ['Wall_4x15_Wainscot_BrickWhite-Wood_SM_Merged'] UStaticMeshComponent
---@field WoodPlank_4x4_Floor_A UStaticMeshComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Union__ UStaticMeshComponent
---@field Lionhead_SM UStaticMeshComponent
---@field Wood_Window_K_Shutter UStaticMeshComponent
---@field Wood_Window_K_Shutter1 UStaticMeshComponent
---@field Wall_2x2_Window_ExposedBrick_SM_Union_ UStaticMeshComponent
---@field RSTTrapGridBox7 URSTTrapGridBoxComponent
---@field BP USceneComponent
---@field Props USceneComponent
---@field TrapGrid USceneComponent
---@field Collision USceneComponent
---@field Geo USceneComponent
ABP_FishMarket_UpTownShop_A_C = {}
