---@meta

---@class ABP_FishMarket_Uptown_ClockTower_C : ABP_OMDTrapGrid_C
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field Nav USceneComponent
---@field Spike_Metal_Gothic_Base3 UStaticMeshComponent
---@field Column_Pointed_Deco_A_SM UStaticMeshComponent
---@field ['Wall+Gable_25x4_Brick_SM1'] UStaticMeshComponent
---@field Spike_Metal_Gothic_Base UStaticMeshComponent
---@field Spike_Metal_Gothic_Base1 UStaticMeshComponent
---@field Spike_Metal_Gothic_Base2 UStaticMeshComponent
---@field ['Wall+Gable_25x4_Brick_SM'] UStaticMeshComponent
---@field Awning_B_LightBlue_SM_Merge UStaticMeshComponent
---@field Column_Pointed_Deco_A_SM1 UStaticMeshComponent
---@field RSTTrapGridBox56 URSTTrapGridBoxComponent
---@field RSTTrapGridBox55 URSTTrapGridBoxComponent
---@field RSTTrapGridBox54 URSTTrapGridBoxComponent
---@field RSTTrapGridBox53 URSTTrapGridBoxComponent
---@field RSTTrapGridBox52 URSTTrapGridBoxComponent
---@field RSTTrapGridBox51 URSTTrapGridBoxComponent
---@field RSTTrapGridBox41 URSTTrapGridBoxComponent
---@field RSTTrapGridBox35 URSTTrapGridBoxComponent
---@field RSTTrapGridBox34 URSTTrapGridBoxComponent
---@field RSTTrapGridBox33 URSTTrapGridBoxComponent
---@field Column_Square_1_4_StoneWall_SM3 UStaticMeshComponent
---@field Roof_2x3x2_Half_Extend_Multi_LightBlue_SM_Union_1 UStaticMeshComponent
---@field Column_Square_1_4_StoneWall_SM1 UStaticMeshComponent
---@field Wall_3x15_ExposedBrick_Gray_SM1 UStaticMeshComponent
---@field Wall_3x15_ExposedBrick_Gray_SM UStaticMeshComponent
---@field ColumnTrim_CastStone_900W9 UStaticMeshComponent
---@field Roof_2x3x2_Half_Extend_Multi_LightBlue_SM_Union_ UStaticMeshComponent
---@field ColumnTrim_CastStone_900W10 UStaticMeshComponent
---@field ColumnTrim_CastStone_900W8 UStaticMeshComponent
---@field Tower_Rec_Roof_LightBlue_SM_Union UStaticMeshComponent
---@field SM_roof_07_RoofA1 UStaticMeshComponent
---@field RSTTrapGridBox37 URSTTrapGridBoxComponent
---@field RSTTrapGridBox36 URSTTrapGridBoxComponent
---@field RSTTrapGridBox32 URSTTrapGridBoxComponent
---@field RSTTrapGridBox31 URSTTrapGridBoxComponent
---@field RSTTrapGridBox30 URSTTrapGridBoxComponent
---@field RSTTrapGridBox29 URSTTrapGridBoxComponent
---@field ColumnTrim_CastStone_900W2 UStaticMeshComponent
---@field ColumnTrim_CastStone_900W1 UStaticMeshComponent
---@field ColumnTrim_CastStone_900W UStaticMeshComponent
---@field SM_roof_07_RoofA UStaticMeshComponent
---@field RSTTrapGridBox28 URSTTrapGridBoxComponent
---@field Geo USceneComponent
---@field TrapGrid USceneComponent
---@field Collision USceneComponent
ABP_FishMarket_Uptown_ClockTower_C = {}



