---@meta

---@class ABP_FishMarket_Bridge_D_C : ABP_OMDTrapGrid_C
---@field Column_Square_Taper_1_4_B_StoneWall_SM1 UStaticMeshComponent
---@field Column_Square_Taper_1_4_B_StoneWall_SM UStaticMeshComponent
---@field Crenellation_Coastal_4x_SM1 UStaticMeshComponent
---@field Crenellation_Coastal_4x_SM UStaticMeshComponent
---@field Stair_1x2_StoneWallBlock_SM2 UStaticMeshComponent
---@field Stair_1x2_StoneWallBlock_SM1 UStaticMeshComponent
---@field Wall_StoneWall_Castle_2x2_SM UStaticMeshComponent
---@field Wall_StoneWall_Castle_2x2_SM1 UStaticMeshComponent
---@field ArchWall_4x2_StoneWall_SM1 UStaticMeshComponent
---@field ArchWall_4x2_StoneWall_SM UStaticMeshComponent
---@field RSTTrapGridBox10 URSTTrapGridBoxComponent
---@field WoodPlank_2x2_Floor_A3 UStaticMeshComponent
---@field WoodPlank_2x2_Floor_A2 UStaticMeshComponent
---@field WoodPlank_2x2_Floor_A1 UStaticMeshComponent
---@field WoodPlank_2x2_Floor_A UStaticMeshComponent
---@field RSTTrapGridBox9 URSTTrapGridBoxComponent
---@field Wood_Plank_900W_A_Light UStaticMeshComponent
---@field Wood_Plank_900W_A_Light4 UStaticMeshComponent
---@field Wood_Plank_900W_A_Light2 UStaticMeshComponent
---@field Wood_Plank_900W_A_Light6 UStaticMeshComponent
---@field Wood_Plank_900W_A_Light1 UStaticMeshComponent
---@field Wood_Plank_900W_A_Light5 UStaticMeshComponent
---@field Wood_Plank_900W_A_Light3 UStaticMeshComponent
---@field RSTTrapGridBox8 URSTTrapGridBoxComponent
---@field RSTTrapGridBox7 URSTTrapGridBoxComponent
---@field Collision USceneComponent
---@field TrapGrid USceneComponent
---@field Geo USceneComponent
ABP_FishMarket_Bridge_D_C = {}
