---@meta

---@class ABP_FishMarket_Tower_Mortar_A_C : ABP_OMDTrapGrid_C
---@field RSTTrapGridBox18 URSTTrapGridBoxComponent
---@field RSTTrapGridBox17 URSTTrapGridBoxComponent
---@field RSTTrapGridBox16 URSTTrapGridBoxComponent
---@field RSTTrapGridBox15 URSTTrapGridBoxComponent
---@field Fortress_Coastal_GateTower_Base_SM5 UStaticMeshComponent
---@field Fortress_Coastal_GateTower_Base_SM4 UStaticMeshComponent
---@field Fortress_Coastal_GateTower_Base_SM3 UStaticMeshComponent
---@field Fortress_Coastal_GateTower_Base_SM2 UStaticMeshComponent
---@field RSTTrapGridBox14 URSTTrapGridBoxComponent
---@field Wood_Window_J_Light UStaticMeshComponent
---@field Window_Pointed_2x_C UStaticMeshComponent
---@field Box UBoxComponent
---@field RSTTrapGridBox13 URSTTrapGridBoxComponent
---@field RSTTrapGridBox12 URSTTrapGridBoxComponent
---@field RSTTrapGridBox11 URSTTrapGridBoxComponent
---@field Fortress_Coastal_GateTower_SM UStaticMeshComponent
---@field Column_Square_1_2_StoneWall_SM1 UStaticMeshComponent
---@field RSTTrapGridBox10 URSTTrapGridBoxComponent
---@field Fortress_Coastal_GateTower_Base_SM1 UStaticMeshComponent
---@field Fortress_Coastal_GateTower_Base_SM UStaticMeshComponent
---@field Column_Square_1_2_StoneWall_SM UStaticMeshComponent
---@field RSTTrapGridBox9 URSTTrapGridBoxComponent
---@field Collision USceneComponent
---@field TrapGrid USceneComponent
---@field Geo USceneComponent
ABP_FishMarket_Tower_Mortar_A_C = {}
