---@meta

---@class ABP_Fountain_01_C : ABP_OMDTrapGrid_C
---@field NS_Fountain_Pool_Ripple UNiagaraComponent
---@field NS_Fountain_Spout_Splash_04 UNiagaraComponent
---@field NS_Fountain_Spout_Splash_03 UNiagaraComponent
---@field NS_Fountain_Spout_Splash_02 UNiagaraComponent
---@field NS_Fountain_Spout_Splash_01 UNiagaraComponent
---@field Water_Pool UStaticMeshComponent
---@field NS_Fountain_Spout_04 UNiagaraComponent
---@field NS_Fountain_Spout_03 UNiagaraComponent
---@field NS_Fountain_Spout_02 UNiagaraComponent
---@field NS_Fountain_Spout_01 UNiagaraComponent
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field RSTTrapGridBox3 URSTTrapGridBoxComponent
---@field RSTTrapGridBox2 URSTTrapGridBoxComponent
---@field RSTTrapGridBox1 URSTTrapGridBoxComponent
---@field RSTTrapGridBox URSTTrapGridBoxComponent
---@field SM_MERGED_Garden_Pillar_1x1_Planter_B UStaticMeshComponent
---@field Metal_Trim_Straight_Deco_3 UStaticMeshComponent
---@field Metal_Trim_Straight_Deco_2 UStaticMeshComponent
---@field Metal_Trim_Straight_Deco_1 UStaticMeshComponent
---@field Metal_Trim_Straight_Deco_ UStaticMeshComponent
---@field Hero_Fountain_A_SM UStaticMeshComponent
ABP_Fountain_01_C = {}
