---@meta

---@class ABP_Fountain_Base_Square_3x3_A_C : ABP_OMDTrapGrid_C
---@field Box3 UBoxComponent
---@field Box2 UBoxComponent
---@field Box1 UBoxComponent
---@field Box UBoxComponent
---@field ASN_FishSpout3 UStaticMeshComponent
---@field ASN_FishSpout2 UStaticMeshComponent
---@field ASN_FishSpout1 UStaticMeshComponent
---@field ASN_FishSpout UStaticMeshComponent
---@field Cylinder1 UStaticMeshComponent
---@field Cylinder UStaticMeshComponent
---@field SM_fountain_part_02 UStaticMeshComponent
---@field SM_fountain_part_01 UStaticMeshComponent
---@field Floor_Terracotta_3x3_A_SM UStaticMeshComponent
---@field Floor_05x2_PatternA1_SM_TrimA4 UStaticMeshComponent
---@field Floor_05x2_PatternA1_SM_TrimA3 UStaticMeshComponent
---@field Floor_05x2_PatternA1_SM_TrimA2 UStaticMeshComponent
---@field Floor_05x2_PatternA1_SM_TrimA1 UStaticMeshComponent
---@field Wall03 URSTTrapGridBoxComponent
---@field Wall02 URSTTrapGridBoxComponent
---@field Wall01 URSTTrapGridBoxComponent
---@field Tower_Square_Stone_Castle_Courtyard_3x3_A UStaticMeshComponent
---@field Wall00 URSTTrapGridBoxComponent
ABP_Fountain_Base_Square_3x3_A_C = {}
