---@meta

---@class ABP_FishVendorStall_Cross_B_Merged_C : ABP_OMDTrapGrid_C
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field Nav USceneComponent
---@field Vendor_Stall_Awning_B_Fabric_SM3 UStaticMeshComponent
---@field Vendor_Stall_Awning_B_Fabric_SM2 UStaticMeshComponent
---@field Vendor_Stall_Awning_B_Fabric_SM1 UStaticMeshComponent
---@field Vendor_Stall_Awning_B_Fabric_SM UStaticMeshComponent
---@field Vendor_Stall_Awning_B_Fabric_Center_SM UStaticMeshComponent
---@field Vendor_Stall_Awning_B_WoodFrame_SM UStaticMeshComponent
---@field FishVendorStall_Cross_SM UStaticMeshComponent
---@field Floor_2x2_Plaza_PatternA1_SM_EXHeightTest_Warp UStaticMeshComponent
---@field Decal_Top UDecalComponent
---@field Decal UDecalComponent
---@field Wall09 URSTTrapGridBoxComponent
---@field Wall08 URSTTrapGridBoxComponent
---@field Wall07 URSTTrapGridBoxComponent
---@field Wall06 URSTTrapGridBoxComponent
---@field Wall05 URSTTrapGridBoxComponent
---@field Wall04 URSTTrapGridBoxComponent
---@field Collision USceneComponent
---@field Wall03 URSTTrapGridBoxComponent
---@field Wall02 URSTTrapGridBoxComponent
---@field Props USceneComponent
---@field Geometry USceneComponent
---@field TrapGrid USceneComponent
---@field SharedRoot USceneComponent
ABP_FishVendorStall_Cross_B_Merged_C = {}
