---@meta

---@class ABP_FishMarket_Uptown_Ground_Street_Alt_C : ABP_OMDTrapGrid_C
---@field RSTTrapGridBox11 URSTTrapGridBoxComponent
---@field RSTTrapGridBox10 URSTTrapGridBoxComponent
---@field Floor_2x2_Plaza_PatternD_SM3 UStaticMeshComponent
---@field Floor_2x2_Plaza_PatternD_SM2 UStaticMeshComponent
---@field Floor_2x2_Plaza_PatternD_SM1 UStaticMeshComponent
---@field Floor_2x2_Plaza_PatternD_SM UStaticMeshComponent
---@field Floor_Tile_T_FishMarket_UptownStreet_SM UStaticMeshComponent
---@field Floor_Tile_Straight_FishMarket_UptownStreet_SM6 UStaticMeshComponent
---@field Floor_Tile_Straight_FishMarket_UptownStreet_SM5 UStaticMeshComponent
---@field Floor_Tile_Straight_FishMarket_UptownStreet_SM4 UStaticMeshComponent
---@field Floor_Tile_Straight_FishMarket_UptownStreet_SM3 UStaticMeshComponent
---@field Floor_Tile_Straight_FishMarket_UptownStreet_SM2 UStaticMeshComponent
---@field Floor_Tile_Straight_FishMarket_UptownStreet_SM1 UStaticMeshComponent
---@field Floor_Tile_Straight_FishMarket_UptownStreet_SM UStaticMeshComponent
---@field Floor_Tile_4wayAlt_B_FishMarket_UptownStreet_SM UStaticMeshComponent
---@field Floor_Tile_4wayAlt_A_FishMarket_UptownStreet_SM UStaticMeshComponent
---@field RSTTrapGridBox9 URSTTrapGridBoxComponent
---@field RSTTrapGridBox8 URSTTrapGridBoxComponent
---@field Collision USceneComponent
---@field TrapGrid USceneComponent
---@field Geo USceneComponent
ABP_FishMarket_Uptown_Ground_Street_Alt_C = {}
