---@meta

---@class ABP_Garden_Pillar_D_C : ABP_OMDTrapGrid_C
---@field Column_BaseD_CastStone1 UStaticMeshComponent
---@field Cren_Stepped_Short_CS17 UStaticMeshComponent
---@field Cren_Stepped_Short_CS16 UStaticMeshComponent
---@field Column_BaseD_CastStone6 UStaticMeshComponent
---@field SupportBlock31 UStaticMeshComponent
---@field SupportBlock30 UStaticMeshComponent
---@field SupportBlock34 UStaticMeshComponent
---@field SupportBlock33 UStaticMeshComponent
---@field TowerTop_Pointed_Trim_3x_SM17 UStaticMeshComponent
---@field TowerTop_Pointed_Trim_3x_SM16 UStaticMeshComponent
---@field TowerTop_Pointed_Trim_3x_SM15 UStaticMeshComponent
---@field TowerTop_Pointed_Trim_3x_SM12 UStaticMeshComponent
---@field TowerTop_Pointed_Trim_3x_SM11 UStaticMeshComponent
---@field TowerTop_Pointed_Trim_3x_SM10 UStaticMeshComponent
---@field TowerTop_Pointed_Trim_3x_SM9 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W11 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W9 UStaticMeshComponent
---@field Cren_Stepped_Short_CS12 UStaticMeshComponent
---@field Cren_Stepped_Short_CS11 UStaticMeshComponent
---@field Cren_Stepped_Short_CS9 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W3 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W6 UStaticMeshComponent
---@field Window_Pointed_1x_Trim3 UStaticMeshComponent
---@field Window_Pointed_1x_Trim2 UStaticMeshComponent
---@field Window_Pointed_1x_Trim1 UStaticMeshComponent
---@field Window_Pointed_1x_Trim UStaticMeshComponent
---@field Column_BaseD_CastStone UStaticMeshComponent
---@field Column_Sec_1_2_FB UStaticMeshComponent
---@field Wall03 URSTTrapGridBoxComponent
---@field Wall02 URSTTrapGridBoxComponent
---@field TowerTop_Pointed_Trim_3x_SM2 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W2 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W1 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W UStaticMeshComponent
---@field ColumnTrim_CastStone_600W5 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W4 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W3 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W2 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W1 UStaticMeshComponent
---@field Wall00 URSTTrapGridBoxComponent
---@field Box_Collision UBoxComponent
---@field Collision USceneComponent
---@field Geometry USceneComponent
---@field TrapGrid USceneComponent
ABP_Garden_Pillar_D_C = {}



