---@meta

---@class ABP_Garden_Wing_Tunnel_A_C : ABP_OMDTrapGrid_C
---@field RSTTrapGridBox5 URSTTrapGridBoxComponent
---@field RSTTrapGridBox4 URSTTrapGridBoxComponent
---@field Wall_4x4_Stonewall_SM13 UStaticMeshComponent
---@field Wall_4x4_Stonewall_SM12 UStaticMeshComponent
---@field Wall_4x4_Stonewall_SM11 UStaticMeshComponent
---@field Wall_4x4_Stonewall_SM10 UStaticMeshComponent
---@field Wall_4x4_Stonewall_SM7 UStaticMeshComponent
---@field Wall_4x4_Stonewall_SM5 UStaticMeshComponent
---@field Wall_4x4_Stonewall_SM4 UStaticMeshComponent
---@field RSTTrapGridBox3 URSTTrapGridBoxComponent
---@field RSTTrapGridBox2 URSTTrapGridBoxComponent
---@field RSTTrapGridBox1 URSTTrapGridBoxComponent
---@field RSTTrapGridBox URSTTrapGridBoxComponent
---@field Stair_1x4_StoneWallBlock_SM UStaticMeshComponent
---@field Floor_4x4_StoneBlock_SM3 UStaticMeshComponent
---@field Floor_4x4_StoneBlock_SM2 UStaticMeshComponent
---@field Floor_4x4_StoneBlock_SM1 UStaticMeshComponent
---@field Floor_4x4_StoneBlock_SM UStaticMeshComponent
---@field Wall_4x4_Stonewall_SM2 UStaticMeshComponent
---@field Props USceneComponent
ABP_Garden_Wing_Tunnel_A_C = {}
