---@meta

---@class ABP_Gardens_Planter_1x2_A_C : ABP_OMDTrapGrid_C
---@field Bush_Triangle_High_05_SM2 UStaticMeshComponent
---@field Bush_Triangle_High_03_SM UStaticMeshComponent
---@field Bush_Triangle_High_05_SM1 UStaticMeshComponent
---@field Bush_Triangle_High_05_SM UStaticMeshComponent
---@field FishMarket_Ceramic_03 UStaticMeshComponent
---@field Props_Pots_04 UStaticMeshComponent
---@field FishMarket_Ceramic_02 UStaticMeshComponent
---@field RailingCornerA3 UStaticMeshComponent
---@field RailingCornerA2 UStaticMeshComponent
---@field RailingCornerA1 UStaticMeshComponent
---@field RailingCornerA UStaticMeshComponent
---@field ColumnTrim_CastStone_600W3 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W2 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W1 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W UStaticMeshComponent
---@field Ceiling URSTTrapGridBoxComponent
---@field Floor_1x2_PatternC1_SM UStaticMeshComponent
ABP_Gardens_Planter_1x2_A_C = {}
