---@meta

---@class ABP_Garden_Wall_Half_Planter_A_C : ABP_OMDTrapGrid_C
---@field ColumnTrim_CastStone_300W15 UStaticMeshComponent
---@field Wall01 URSTTrapGridBoxComponent
---@field ColumnTrim_CastStone_300W23 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W22 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W21 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W20 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W18 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W16 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W14 UStaticMeshComponent
---@field Floor_Herringbone_2x2_SM UStaticMeshComponent
---@field Wall_Sec_2_2_RB7 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W13 UStaticMeshComponent
---@field Wall_Sec_2_2_RB6 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W12 UStaticMeshComponent
---@field Wall_Sec_2_2_RB3 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W9 UStaticMeshComponent
---@field TowerTop_Pointed_Trim_3x_SM8 UStaticMeshComponent
---@field TowerTop_Pointed_Trim_3x_SM7 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W7 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W4 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W3 UStaticMeshComponent
---@field SupportBlock8 UStaticMeshComponent
---@field SupportBlock7 UStaticMeshComponent
---@field SupportBlock6 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W6 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W5 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W2 UStaticMeshComponent
---@field TowerTop_Pointed_Trim_3x_SM5 UStaticMeshComponent
---@field TowerTop_Pointed_Trim_3x_SM4 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W13 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W12 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W11 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W10 UStaticMeshComponent
---@field Wall03 URSTTrapGridBoxComponent
---@field Wall02 URSTTrapGridBoxComponent
---@field TowerTop_Pointed_Trim_3x_SM3 UStaticMeshComponent
---@field TowerTop_Pointed_Trim_3x_SM2 UStaticMeshComponent
---@field SupportBlock2 UStaticMeshComponent
---@field SupportBlock1 UStaticMeshComponent
---@field SupportBlock UStaticMeshComponent
---@field Wall_Sec_2_2_RB2 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W UStaticMeshComponent
---@field ColumnTrim_CastStone_600W4 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W1 UStaticMeshComponent
---@field Wall00 URSTTrapGridBoxComponent
---@field Box_Collision UBoxComponent
---@field Collision USceneComponent
---@field Geometry USceneComponent
---@field TrapGrid USceneComponent
ABP_Garden_Wall_Half_Planter_A_C = {}



