---@meta

---@class ABP_Library_Bookshelf_2x2_Wall_B_Merged_C : ABP_OMDTrapGrid_C
---@field Bookshelf_Half_C16 UStaticMeshComponent
---@field Bookstack_A9 UStaticMeshComponent
---@field Bookshelf_Quarter_A7 UStaticMeshComponent
---@field Bookstack_A8 UStaticMeshComponent
---@field Bookshelf_Quarter_A8 UStaticMeshComponent
---@field Bookshelf_Half_A2 UStaticMeshComponent
---@field Bookshelf_Quarter_A5 UStaticMeshComponent
---@field Bookshelf_Half_C4 UStaticMeshComponent
---@field Bookstack_B_Bookstack_B1 UStaticMeshComponent
---@field Bookshelf_Half_C5 UStaticMeshComponent
---@field Bookshelf_Quarter_A6 UStaticMeshComponent
---@field Bookshelf_Half_C17 UStaticMeshComponent
---@field Bookstack_A7 UStaticMeshComponent
---@field Bookshelf_Half_B1 UStaticMeshComponent
---@field Bookshelf_Half_A8 UStaticMeshComponent
---@field Bookshelf_Quarter_A3 UStaticMeshComponent
---@field Bookshelf_Half_C3 UStaticMeshComponent
---@field Bookshelf_Quarter_A4 UStaticMeshComponent
---@field Bookstack_A2 UStaticMeshComponent
---@field Bookshelf_Half_C2 UStaticMeshComponent
---@field Bookshelf_Quarter_A2 UStaticMeshComponent
---@field Bookshelf_Half_B5 UStaticMeshComponent
---@field BookShelf_Half_A1 UStaticMeshComponent
---@field SM_MERGED_BP_Library_Bookshelf_2x2_Wall_NoTop_Merge UStaticMeshComponent
---@field RSTTrapGridBox02 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Geo_Shelf USceneComponent
---@field Box_Collision_Middle UBoxComponent
ABP_Library_Bookshelf_2x2_Wall_B_Merged_C = {}
