---@meta

---@class ABP_Library_Bookshelf_Manor_SmallBooks_Back_C : ABP_OMDTrapGrid_C
---@field StaticMesh2 UStaticMeshComponent
---@field StaticMesh UStaticMeshComponent
---@field StaticMesh1 UStaticMeshComponent
---@field StaticMesh79 UStaticMeshComponent
---@field StaticMesh76 UStaticMeshComponent
---@field StaticMesh75 UStaticMeshComponent
---@field StaticMesh74 UStaticMeshComponent
---@field StaticMesh73 UStaticMeshComponent
---@field StaticMesh72 UStaticMeshComponent
---@field StaticMesh71 UStaticMeshComponent
---@field StaticMesh70 UStaticMeshComponent
---@field StaticMesh69 UStaticMeshComponent
---@field StaticMesh68 UStaticMeshComponent
---@field StaticMesh67 UStaticMeshComponent
---@field StaticMesh66 UStaticMeshComponent
---@field StaticMesh65 UStaticMeshComponent
---@field StaticMesh64 UStaticMeshComponent
---@field StaticMesh43 UStaticMeshComponent
---@field StaticMesh62 UStaticMeshComponent
---@field StaticMesh61 UStaticMeshComponent
---@field StaticMesh60 UStaticMeshComponent
---@field StaticMesh56 UStaticMeshComponent
---@field StaticMesh54 UStaticMeshComponent
---@field StaticMesh53 UStaticMeshComponent
---@field StaticMesh52 UStaticMeshComponent
---@field StaticMesh50 UStaticMeshComponent
---@field StaticMesh49 UStaticMeshComponent
---@field StaticMesh48 UStaticMeshComponent
---@field StaticMesh44 UStaticMeshComponent
---@field StaticMesh41 UStaticMeshComponent
---@field StaticMesh35 UStaticMeshComponent
---@field StaticMesh34 UStaticMeshComponent
---@field StaticMesh23 UStaticMeshComponent
---@field StaticMesh32 UStaticMeshComponent
---@field StaticMesh25 UStaticMeshComponent
---@field Books_2 USceneComponent
---@field StaticMesh13 UStaticMeshComponent
---@field StaticMesh12 UStaticMeshComponent
---@field StaticMesh11 UStaticMeshComponent
---@field StaticMesh5 UStaticMeshComponent
---@field StaticMesh10 UStaticMeshComponent
---@field StaticMesh8 UStaticMeshComponent
---@field StaticMesh7 UStaticMeshComponent
---@field StaticMesh6 UStaticMeshComponent
---@field StaticMesh9 UStaticMeshComponent
---@field StaticMesh22 UStaticMeshComponent
---@field StaticMesh21 UStaticMeshComponent
---@field StaticMesh15 UStaticMeshComponent
---@field StaticMesh20 UStaticMeshComponent
---@field StaticMesh18 UStaticMeshComponent
---@field StaticMesh17 UStaticMeshComponent
---@field StaticMesh16 UStaticMeshComponent
---@field StaticMesh19 UStaticMeshComponent
---@field StaticMesh3 UStaticMeshComponent
---@field StaticMesh4 UStaticMeshComponent
---@field StaticMesh14 UStaticMeshComponent
---@field Books_1 USceneComponent
ABP_Library_Bookshelf_Manor_SmallBooks_Back_C = {}



