---@meta

---@class ABP_Library_Gate_Iron_Wall_C : ABP_OMDTrapGrid_C
---@field ColumnTrim_CastStone_1800W1 UStaticMeshComponent
---@field ColumnTrim_CastStone_1800W UStaticMeshComponent
---@field Fencing_2x2_RodIron_Garden_Curved UStaticMeshComponent
---@field Window_Pointed_Sil_SM6 UStaticMeshComponent
---@field Window_Pointed_Sil_SM12 UStaticMeshComponent
---@field Window_Pointed_Sil_SM11 UStaticMeshComponent
---@field Window_Pointed_Sil_SM10 UStaticMeshComponent
---@field Window_Pointed_Sil_SM9 UStaticMeshComponent
---@field Window_Pointed_1x_Trim13 UStaticMeshComponent
---@field Window_Pointed_1x_Trim12 UStaticMeshComponent
---@field Window_Pointed_1x_Trim11 UStaticMeshComponent
---@field Window_Pointed_1x_Trim10 UStaticMeshComponent
---@field Window_Pointed_1x_Trim19 UStaticMeshComponent
---@field Window_Pointed_1x_Trim18 UStaticMeshComponent
---@field Window_Pointed_1x_Trim17 UStaticMeshComponent
---@field Window_Pointed_1x_Trim16 UStaticMeshComponent
---@field Drawbridge_SpikeWall_HingeA5 UStaticMeshComponent
---@field Drawbridge_SpikeWall_HingeA4 UStaticMeshComponent
---@field Drawbridge_SpikeWall_HingeA3 UStaticMeshComponent
---@field Drawbridge_SpikeWall_HingeA2 UStaticMeshComponent
---@field Drawbridge_SpikeWall_HingeA1 UStaticMeshComponent
---@field Drawbridge_SpikySupport_SM UStaticMeshComponent
---@field Drawbridge_SpikeWall_HingeA UStaticMeshComponent
---@field Arch_1x4_FoundationBlock UStaticMeshComponent
---@field Window_Pointed_1x_Trim2 UStaticMeshComponent
---@field Window_Pointed_1x_Trim1 UStaticMeshComponent
---@field Window_Pointed_1x_Trim3 UStaticMeshComponent
---@field Window_Pointed_Sil_SM5 UStaticMeshComponent
---@field Window_Pointed_1x_Trim UStaticMeshComponent
---@field TrapGrid USceneComponent
---@field Geo_Shelf USceneComponent
---@field Box_Collision_Middle UBoxComponent
ABP_Library_Gate_Iron_Wall_C = {}
