---@meta

---@class ABP_Library_Doorway_2x2_Wall_C : ABP_OMDTrapGrid_C
---@field Box_Collision_Middle1 UBoxComponent
---@field Window_Pointed_Sil_SM7 UStaticMeshComponent
---@field Window_Pointed_Sil_SM6 UStaticMeshComponent
---@field Cren_Stepped_Short_Five_CS1 UStaticMeshComponent
---@field Cren_Stepped_Short_Five_CS UStaticMeshComponent
---@field Window_Pointed_1x_Trim9 UStaticMeshComponent
---@field Window_Pointed_1x_Trim8 UStaticMeshComponent
---@field Arch_1x4_FoundationBlock UStaticMeshComponent
---@field SM_doorway_03 UStaticMeshComponent
---@field Window_Pointed_1x_Trim7 UStaticMeshComponent
---@field Window_Pointed_1x_Trim6 UStaticMeshComponent
---@field Window_Pointed_1x_Trim2 UStaticMeshComponent
---@field Window_Pointed_1x_Trim1 UStaticMeshComponent
---@field Window_Pointed_1x_Trim5 UStaticMeshComponent
---@field Window_Pointed_1x_Trim3 UStaticMeshComponent
---@field Window_Pointed_Sil_SM5 UStaticMeshComponent
---@field SM_door_03 UStaticMeshComponent
---@field Window_Pointed_1x_Trim UStaticMeshComponent
---@field Window_Pointed_1x_Trim4 UStaticMeshComponent
---@field SM_door_04 UStaticMeshComponent
---@field RSTTrapGridBox02 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Geo_Shelf USceneComponent
---@field Box_Collision_Middle UBoxComponent
ABP_Library_Doorway_2x2_Wall_C = {}
