---@meta

---@class ABP_Observatory_BeachHunts_01_C : AActor
---@field BP_Wood_Crate_65A_A_Breakable UChildActorComponent
---@field FishMarket_Garlic_02 UStaticMeshComponent
---@field FishMarket_Onion_02 UStaticMeshComponent
---@field OrbLight_Coastal_B_SM1 UStaticMeshComponent
---@field OrbLight_Coastal_B_SM UStaticMeshComponent
---@field BookShelf_Half_A UStaticMeshComponent
---@field FishMarket_Sack_01 UStaticMeshComponent
---@field Rugs_Blankets_Textiles_M_01 UStaticMeshComponent
---@field FishMarket_Bag_01 UStaticMeshComponent
---@field Wood_KitchenHutch_A UStaticMeshComponent
---@field Observatory_BeachHuts_Structure_01 UStaticMeshComponent
---@field Observatory_BeachHuts_Base_01 UStaticMeshComponent
---@field FishMarket_Ceramic_01 UStaticMeshComponent
---@field Observatory_BeachHutsBuilding_Telescope_01 UStaticMeshComponent
---@field Book_C_Book_C1 UStaticMeshComponent
---@field Book_C_Book_C UStaticMeshComponent
---@field Book_B_Book_B UStaticMeshComponent
---@field Observatory_BeachHuts_Roof_01 UStaticMeshComponent
---@field Geo USceneComponent
ABP_Observatory_BeachHunts_01_C = {}
