---@meta

---@class ABP_Observatory_DockHouse_F_C : ABP_OMDTrapGrid_C
---@field Wall_15x2_Wainscot_ExposedBrick_SM_Merge1 UStaticMeshComponent
---@field Box UBoxComponent
---@field Wood_Platform_300x300_A_Light3 UStaticMeshComponent
---@field Wood_Square_900W_A_light_NoTaper5 UStaticMeshComponent
---@field Wood_Square_900W_A_light_NoTaper8 UStaticMeshComponent
---@field Wood_Square_900W_A_light_NoTaper9 UStaticMeshComponent
---@field Wall_15x2_Wainscot_ExposedBrick_SM_Merge UStaticMeshComponent
---@field Wood_Platform_300x300_A_Light6 UStaticMeshComponent
---@field Wood_Square_900W_A_light_NoTaper7 UStaticMeshComponent
---@field RSTTrapGridBox4 URSTTrapGridBoxComponent
---@field RSTTrapGridBox2 URSTTrapGridBoxComponent
---@field RSTTrapGridBox1 URSTTrapGridBoxComponent
---@field Wall_4x2_Wainscot_Wood_SM_Deco_Counter_Merged UStaticMeshComponent
---@field BP USceneComponent
---@field RSTTrapGridBox URSTTrapGridBoxComponent
---@field Props USceneComponent
---@field TrapGrid USceneComponent
---@field Collision USceneComponent
---@field Geo USceneComponent
ABP_Observatory_DockHouse_F_C = {}
