---@meta

---@class ABP_Orc_Ship_Ironclad_FrontExit_Spawner_C : AActor
---@field NavPowerExclusion2 UNavPowerExclusionComponent
---@field NavPowerExclusion1 UNavPowerExclusionComponent
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field NavGen USceneComponent
---@field Orc_ShipIronClad_NavGen_SM UStaticMeshComponent
---@field Orc_ShipIronClad_A_03_Door_SM3 UStaticMeshComponent
---@field Orc_ShipIronClad_A_03_Door_SM2 UStaticMeshComponent
---@field Orc_ShipIronClad_A_03_Door_SM1 UStaticMeshComponent
---@field Orc_ShipIronClad_A_03_Door_SM UStaticMeshComponent
---@field Orc_ShipIronClad_DoorOpen_SM1 UStaticMeshComponent
---@field Orc_ShipIronClad_DoorOpen_SM UStaticMeshComponent
---@field Orc_Sail UStaticMeshComponent
---@field ForceField_VFX2 UStaticMeshComponent
---@field Orc_ShipIronClad_FrontExit_SM UStaticMeshComponent
---@field FishPaste_SM2 UStaticMeshComponent
---@field FishHanging_SM1 UStaticMeshComponent
---@field HangingMeat_C_SM UStaticMeshComponent
---@field FishHanging_SM UStaticMeshComponent
---@field FishPaste_SM UStaticMeshComponent
---@field Wood_Crate_65A_A2 UStaticMeshComponent
---@field Wood_TopBarrel_A UStaticMeshComponent
---@field Wood_Barrel_A UStaticMeshComponent
---@field Wood_Crate_65A_A1 UStaticMeshComponent
---@field Wood_Crate_65A_A UStaticMeshComponent
---@field Wood_Crate_125A_B1 UStaticMeshComponent
---@field Wood_Crate_125A_B UStaticMeshComponent
---@field Metal_Crate_125A_300A_B UStaticMeshComponent
---@field Metal_Crate_125A_300A_B1 UStaticMeshComponent
---@field BlackFog_VFX UStaticMeshComponent
---@field Geo USceneComponent
---@field ForceField_VFX UStaticMeshComponent
---@field FX USceneComponent
---@field DefaultSceneRoot USceneComponent
ABP_Orc_Ship_Ironclad_FrontExit_Spawner_C = {}
