---@meta

---@class ABP_Rift_Platform_Museum_C : ABP_OMDTrapGrid_C
---@field Rift_Base_Box_SM2 UStaticMeshComponent
---@field Rift_Base_Box_SM1 UStaticMeshComponent
---@field Rift_Base_Box_Tmp_SM UStaticMeshComponent
---@field Rift_Base_Box_Tmp_SM1 UStaticMeshComponent
---@field Rift_Base_Box_Tmp_SM2 UStaticMeshComponent
---@field Rift_Base_Box_Tmp_SM3 UStaticMeshComponent
---@field Arrow UArrowComponent
---@field HiddenNavHelperMesh012 UStaticMeshComponent
---@field HiddenNavHelperMesh011 UStaticMeshComponent
---@field HiddenNavHelperMesh010 UStaticMeshComponent
---@field HiddenNavHelperMesh09 UStaticMeshComponent
---@field HiddenNavHelperMesh08 UStaticMeshComponent
---@field HiddenNavHelperMesh07 UStaticMeshComponent
---@field HiddenNavHelperMesh06 UStaticMeshComponent
---@field HiddenNavHelperMesh05 UStaticMeshComponent
---@field HiddenNavHelperMesh04 UStaticMeshComponent
---@field HiddenNavHelperMesh03 UStaticMeshComponent
---@field HiddenNavHelperMesh02 UStaticMeshComponent
---@field HiddenNavHelperMesh01 UStaticMeshComponent
---@field RSTTrapGridBox5 URSTTrapGridBoxComponent
---@field Cube_Hidden UStaticMeshComponent
---@field Box1 UBoxComponent
---@field Box UBoxComponent
---@field RSTTrapGridBox4 URSTTrapGridBoxComponent
---@field RSTTrapGridBox3 URSTTrapGridBoxComponent
---@field RSTTrapGridBox2 URSTTrapGridBoxComponent
---@field RSTTrapGridBox1 URSTTrapGridBoxComponent
---@field TrapGrid USceneComponent
---@field Geo USceneComponent
ABP_Rift_Platform_Museum_C = {}
