---@meta

---@class ABP_Roof_Dome_5x4x3_C : AActor
---@field Wood_Square_300W_A_NoTaper_Light_TempCut3 UStaticMeshComponent
---@field Wood_Square_300W_A_NoTaper_Light_TempCut2 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendA1 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendA UStaticMeshComponent
---@field Wood_Square_300W_A_NoTaper_Light_TempCut UStaticMeshComponent
---@field Wood_Square_300W_A_NoTaper_Light_TempCut1 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendA3 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendA2 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light2 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light1 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light6 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light5 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light1 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light2 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light UStaticMeshComponent
---@field Wood_Plank_600W_A_Light4 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light7 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light3 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light14_StaticMeshComponent4 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light14_StaticMeshComponent6 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light14_StaticMeshComponent5 UStaticMeshComponent
---@field Roof_5x4x3_ShingleC_SM_End_Union12_StaticMeshComponent0 UStaticMeshComponent
---@field Geo USceneComponent
---@field SharedRoot USceneComponent
ABP_Roof_Dome_5x4x3_C = {}
