---@meta

---@class ABP_Vista_Obelisk_Tower_C : ABP_OMDTrapGrid_C
---@field Box UBoxComponent
---@field ColumnB_A_CastStone_1Story7 UStaticMeshComponent
---@field ColumnB_A_CastStone_1Story6 UStaticMeshComponent
---@field ColumnB_A_CastStone_1Story5 UStaticMeshComponent
---@field ColumnB_A_CastStone_1Story4 UStaticMeshComponent
---@field ColumnB_A_CastStone_1Story3 UStaticMeshComponent
---@field ColumnB_A_CastStone_1Story2 UStaticMeshComponent
---@field ColumnB_A_CastStone_1Story1 UStaticMeshComponent
---@field Wood_Window_K_Seablue_Shutter_Left UStaticMeshComponent
---@field Window_Pointed_2x_A UStaticMeshComponent
---@field ColumnB_A_CastStone_1Story UStaticMeshComponent
---@field Fortress_Coastal_GateTower_Roof_SM UStaticMeshComponent
---@field Proto_Fortress_Coastal_Obelisk_SideMount_SM UStaticMeshComponent
---@field Fortress_Coastal_GateTower_Foundation_Trim_SM UStaticMeshComponent
---@field TrapGrid USceneComponent
---@field Prop USceneComponent
---@field Foliage USceneComponent
---@field Geo USceneComponent
ABP_Vista_Obelisk_Tower_C = {}
