---@meta

---@class ABP_Wall_Pantry_Manor_4x2_A_C : ABP_OMDTrapGrid_C
---@field Wood_Square_600W_A_NoTaper_Light3 UStaticMeshComponent
---@field Wood_Square_300W_A_NoTaper_light3 UStaticMeshComponent
---@field Wood_Square_300W_A_NoTaper_light2 UStaticMeshComponent
---@field Wood_Square_300W_A_NoTaper_light1 UStaticMeshComponent
---@field Wood_Square_300W_A_NoTaper_light UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light2 UStaticMeshComponent
---@field Wood_Barrel_A3 UStaticMeshComponent
---@field Wood_Barrel_A2 UStaticMeshComponent
---@field Wood_Barrel_A1 UStaticMeshComponent
---@field Wood_Barrel_A UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light1 UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light UStaticMeshComponent
---@field WoodPlank_4x1_Floor_A1 UStaticMeshComponent
---@field WoodPlank_4x1_Floor_A UStaticMeshComponent
---@field Wall_Bottom_Stone_Castle_Courtyard_4x2_A_SM UStaticMeshComponent
---@field Wall_Bottom_Stone_Castle_Courtyard_1x2_A_SM1 UStaticMeshComponent
---@field Wall_Bottom_Stone_Castle_Courtyard_1x2_A_SM UStaticMeshComponent
---@field Wall_DoorwayWide_Cobblestone_Manor_4x2_A_SM UStaticMeshComponent
---@field trap_wall URSTTrapGridBoxComponent
ABP_Wall_Pantry_Manor_4x2_A_C = {}
