---@meta

---@class ABP_Wood_Platform_1x2_B_C : ABP_OMDTrapGrid_C
---@field NavPowerExclusion UNavPowerExclusionComponent
---@field Wood_Plank_300W_A_Light3 UStaticMeshComponent
---@field Wood_Plank_300W_A_Light2 UStaticMeshComponent
---@field Wood_Plank_300W_A_Light1 UStaticMeshComponent
---@field Wood_Plank_300W_A_Light UStaticMeshComponent
---@field Wall_1x05_Wood_SM_Union5 UStaticMeshComponent
---@field Wall_1x05_Wood_SM_Union4 UStaticMeshComponent
---@field Wall_1x05_Wood_SM_Union3 UStaticMeshComponent
---@field Wall_1x05_Wood_SM_Union2 UStaticMeshComponent
---@field Wall_1x05_Wood_SM_Union1 UStaticMeshComponent
---@field Wall03 URSTTrapGridBoxComponent
---@field Wall02 URSTTrapGridBoxComponent
---@field Wall01 URSTTrapGridBoxComponent
---@field Wall00 URSTTrapGridBoxComponent
---@field Box UBoxComponent
---@field Wood_Plank_600W_A3 UStaticMeshComponent
---@field Wood_Plank_600W_A2 UStaticMeshComponent
---@field Wood_Plank_600W_A1 UStaticMeshComponent
---@field Wood_Plank_600W_A UStaticMeshComponent
---@field Wood_Square_600W_A2 UStaticMeshComponent
---@field Wall_1x05_Wood_SM_Union UStaticMeshComponent
---@field Geometry USceneComponent
ABP_Wood_Platform_1x2_B_C = {}
