---@meta

---@class ABP_Warehouse_17_Walkway_C : AActor
---@field Wood_Log_300W_A16_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Log_300W_A15_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Log_300W_A14_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Log_300W_A13_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Log_300W_A12_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Log_300W_A11_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Log_300W_A10_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Log_300W_A9_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Deco_C9_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Deco_C8_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Deco_C7_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Deco_C5_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Deco_C4_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Deco_C3_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Deco_C2_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Deco_C_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Platform_300x600_A_Light7_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Platform_300x600_A_Light6_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Platform_300x600_A_Light5_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Platform_300x600_A_Light4_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Platform_300x600_A_Light3_StaticMeshComponent0 UStaticMeshComponent
---@field Wood_Platform_300x600_A_Light2_StaticMeshComponent0 UStaticMeshComponent
---@field SharedRoot USceneComponent
ABP_Warehouse_17_Walkway_C = {}
