---@meta

---@class ABP_WallTile_TunnelHoleEnd_2x2_Sewer_C : ABP_OMDTrapGrid_C
---@field Wall_2x2_SM1 UStaticMeshComponent
---@field Wall_2x2_SM UStaticMeshComponent
---@field TunnelLarge_Straight_2x_Bottom_Sewer_SM4 UStaticMeshComponent
---@field TunnelLarge_Straight_2x_Top_Sewer_SM4 UStaticMeshComponent
---@field TunnelLarge_Straight_2x_Top_Sewer_SM3 UStaticMeshComponent
---@field TunnelLarge_Straight_2x_Bottom_Sewer_SM3 UStaticMeshComponent
---@field TunnelLarge_T_4x3_Top_Sewer_SM UStaticMeshComponent
---@field TunnelLarge_T_4x3_Bottom_Sewer_SM UStaticMeshComponent
---@field TunnelLarge_Straight_2x_Bottom_Sewer_SM2 UStaticMeshComponent
---@field TunnelLarge_Straight_2x_Top_Sewer_SM2 UStaticMeshComponent
---@field TunnelLarge_Straight_2x_Bottom_Sewer_SM1 UStaticMeshComponent
---@field TunnelLarge_Straight_2x_Top_Sewer_SM1 UStaticMeshComponent
---@field TunnelLarge_Straight_2x_Top_Sewer_SM UStaticMeshComponent
---@field TunnelLarge_Straight_2x_Bottom_Sewer_SM UStaticMeshComponent
---@field TunnelLarge_EndRing_Sewer_SM UStaticMeshComponent
---@field WallTile_TunnelHole_2x2_Sewer_SM UStaticMeshComponent
---@field trap_wall URSTTrapGridBoxComponent
ABP_WallTile_TunnelHoleEnd_2x2_Sewer_C = {}
