---@meta

---@class ABP_Wall_Stairside_4x2_Wood_C : ABP_OMDTrapGrid_C
---@field Wood_BookShelft_Pillar_600C_06 UStaticMeshComponent
---@field Trap_Wall7 URSTTrapGridBoxComponent
---@field Trap_Wall6 URSTTrapGridBoxComponent
---@field Wood_BookShelft_Pillar_600C_05 UStaticMeshComponent
---@field Wood_BookShelft_Pillar_600C_04 UStaticMeshComponent
---@field Wood_BookShelft_Pillar_600C_03 UStaticMeshComponent
---@field Wood_BookShelft_Pillar_300C_02 UStaticMeshComponent
---@field Metal_Railing_900C UStaticMeshComponent
---@field Wood_BookShelft_Pillar_600C_02 UStaticMeshComponent
---@field Wood_BookShelves_Railing_900C_04 UStaticMeshComponent
---@field Wood_BookShelves_Railing_900C_03 UStaticMeshComponent
---@field Wood_BookShelves_Railing_900C_02 UStaticMeshComponent
---@field Wood_BookShelves_Railing_900C_01 UStaticMeshComponent
---@field Trap_Wall5 URSTTrapGridBoxComponent
---@field Trap_Wall4 URSTTrapGridBoxComponent
---@field Trap_Wall3 URSTTrapGridBoxComponent
---@field Trap_Wall2 URSTTrapGridBoxComponent
---@field Wall_2x1_StairSide_StoneWall_SM UStaticMeshComponent
---@field Wall_2x2_StairSide_StoneWall_SM UStaticMeshComponent
---@field Trap_Wall1 URSTTrapGridBoxComponent
---@field trap_wall URSTTrapGridBoxComponent
ABP_Wall_Stairside_4x2_Wood_C = {}
