---@meta

---@class ABP_Wood_Awning_300W_A_C : ABP_OMDTrapGrid_C
---@field Wood_Plank_300W_A_Light7 UStaticMeshComponent
---@field Wood_Plank_300W_A_Light6 UStaticMeshComponent
---@field Wood_Plank_300W_A_Light5 UStaticMeshComponent
---@field Wood_Plank_300W_A_Light4 UStaticMeshComponent
---@field Wood_Plank_300W_A_Light3 UStaticMeshComponent
---@field Wood_Plank_300W_A_Light2 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendK1 UStaticMeshComponent
---@field Wood_Plank_600W_A_Light_BendK UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light5 UStaticMeshComponent
---@field Roof_2x2x2_Half_Blue_SM_Canopy_Union UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light4 UStaticMeshComponent
---@field Box_CeilingCollision UBoxComponent
---@field Ceiling URSTTrapGridBoxComponent
---@field Wood_Plank_300W_A_Light1 UStaticMeshComponent
---@field Wood_Plank_300W_A_Light UStaticMeshComponent
---@field WoodPlank_2x2_Flooar_A UStaticMeshComponent
---@field Wood_Square_600W_A_NoTaper_Light1 UStaticMeshComponent
---@field Geometry USceneComponent
ABP_Wood_Awning_300W_A_C = {}
