---@meta

---@class ABP_WallTorch_Alchemist_Light_C : AActor
---@field NS_WallTorch_Fire_Blue UNiagaraComponent
---@field AmbEmitter_Torch_LP_SC UAudioComponent
---@field Lighting_Torch_Wall_Wood UStaticMeshComponent
---@field Decal UDecalComponent
---@field Box UBoxComponent
---@field DefaultSceneRoot USceneComponent
---@field StaticLightColorDefault FLinearColor
---@field MoveableLightColorDefault FLinearColor
---@field StaticLightColorVar1 FLinearColor
---@field MoveableLightColorVar1 FLinearColor
---@field FXColorDefault FLinearColor
---@field FXColorVar1 FLinearColor
---@field WallBase LightWallBase::Type
---@field WallBaseVisible boolean
---@field WallBaseNotVisible boolean
---@field Intensity float
---@field MinTime double
---@field MaxTime double
---@field MinFlickerIntensity float
---@field ['New Light Color'] FLinearColor
ABP_WallTorch_Alchemist_Light_C = {}
