---@meta

---@class ABP_Window_Arboretum_StainGlass_XL_C : AActor
---@field Column_BaseB_CastStone1 UStaticMeshComponent
---@field Column_BaseB_CastStone UStaticMeshComponent
---@field Proto_Dome_RiftRoom_C_Window_Glass UStaticMeshComponent
---@field Window_Pointed_1x_Trim5 UStaticMeshComponent
---@field Window_Pointed_2x_Trim_Arch1 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W4 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W3 UStaticMeshComponent
---@field Proto_Dome_RiftRoom_C_Window UStaticMeshComponent
---@field Window_Pointed_2x_Trim_Arch UStaticMeshComponent
---@field Window_Pointed_1x_Trim4 UStaticMeshComponent
---@field Window_Pointed_1x_Trim3 UStaticMeshComponent
---@field Window_Pointed_1x_Trim2 UStaticMeshComponent
---@field Window_Pointed_1x_Trim1 UStaticMeshComponent
---@field Window_Pointed_1x_Trim UStaticMeshComponent
---@field ColumnTrim_CastStone_600W2 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W1 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W UStaticMeshComponent
---@field DefaultSceneRoot USceneComponent
ABP_Window_Arboretum_StainGlass_XL_C = {}
