---@meta

---@class ACastle_Large_Tower_Mortar_B_C : ABP_OMDTrapGrid_C
---@field Roof_Tiled_x1_Base1 UStaticMeshComponent
---@field Cren_1_Half_RB UStaticMeshComponent
---@field Roof_Tiled_x1_Base UStaticMeshComponent
---@field Cren_1_Half_RB1 UStaticMeshComponent
---@field Roof_Tiled_x2_Base UStaticMeshComponent
---@field ColumnBlock_BottomTile_1_FB2 UStaticMeshComponent
---@field ColumnBlock_BottomTile_1_FB4 UStaticMeshComponent
---@field ColumnBlock_BottomTile_1_FB1 UStaticMeshComponent
---@field Roof_Tiled_x1_Base3 UStaticMeshComponent
---@field Roof_Tiled_x2_Base3 UStaticMeshComponent
---@field Cren_1_Half_RB3 UStaticMeshComponent
---@field Cren_1_Half_RB2 UStaticMeshComponent
---@field Roof_Tiled_x2_Base2 UStaticMeshComponent
---@field Roof_Tiled_x2_Base4 UStaticMeshComponent
---@field Roof_Tiled_x1_Base2 UStaticMeshComponent
---@field Crenellation_1_RB4 UStaticMeshComponent
---@field Crenellation_1_RB3 UStaticMeshComponent
---@field Crenellation_1_RB2 UStaticMeshComponent
---@field Crenellation_1_RB UStaticMeshComponent
---@field Tower USceneComponent
ACastle_Large_Tower_Mortar_B_C = {}
