---@meta

---@class ACastle_2x2_Tower_FB_4x_SAND_Trailer_C : ABP_OMDTrapGrid_C
---@field Window_Pointed_TowerTop3 UStaticMeshComponent
---@field Window_Pointed_TowerTop2 UStaticMeshComponent
---@field Window_Pointed_TowerTop1 UStaticMeshComponent
---@field Window_Pointed_TowerTop UStaticMeshComponent
---@field TowerTop_Pointed_SM UStaticMeshComponent
---@field ColumnBlock_BottomTile_1_FB5 UStaticMeshComponent
---@field ColumnBlock_BottomTile_1_FB4 UStaticMeshComponent
---@field ColumnBlock_BottomTile_1_FB2 UStaticMeshComponent
---@field ColumnBlock_BottomTile_1_FB1 UStaticMeshComponent
---@field Wall_Middle_08 URSTTrapGridBoxComponent
---@field Wall_Middle_07 URSTTrapGridBoxComponent
---@field Wall_Middle_06 URSTTrapGridBoxComponent
---@field Wall_Middle_05 URSTTrapGridBoxComponent
---@field Wall_Middle_04 URSTTrapGridBoxComponent
---@field Wall_Middle_03 URSTTrapGridBoxComponent
---@field Wall_Middle_02 URSTTrapGridBoxComponent
---@field Wall_Middle_01 URSTTrapGridBoxComponent
ACastle_2x2_Tower_FB_4x_SAND_Trailer_C = {}
