---@meta

---@class ACeiling_RB_MT_v1_4x4_C : ABP_OMDTrapGrid_C
---@field Floor_4x4_StoneBlock_SM UStaticMeshComponent
---@field Metal_4WayJoint14 UStaticMeshComponent
---@field Metal_4WayJoint13 UStaticMeshComponent
---@field Metal_4WayJoint23 UStaticMeshComponent
---@field Metal_4WayJoint22 UStaticMeshComponent
---@field Metal_4WayJoint21 UStaticMeshComponent
---@field Metal_4WayJoint20 UStaticMeshComponent
---@field Metal_4WayJoint17 UStaticMeshComponent
---@field Metal_4WayJoint18 UStaticMeshComponent
---@field Metal_4WayJoint15 UStaticMeshComponent
---@field Metal_4WayJoint12 UStaticMeshComponent
---@field CastTrim USceneComponent
---@field Metal_4WayJoint16 UStaticMeshComponent
---@field Metal_4WayJoint4 UStaticMeshComponent
---@field Metal_4WayJoint5 UStaticMeshComponent
---@field Metal_4WayJoint UStaticMeshComponent
---@field Metal_4WayJoint10 UStaticMeshComponent
---@field Metal_4WayJoint11 UStaticMeshComponent
---@field Metal_4WayJoint1 UStaticMeshComponent
---@field Metal_4WayJoint19 UStaticMeshComponent
---@field Metal_4WayJoint9 UStaticMeshComponent
---@field Metal_4WayJoint2 UStaticMeshComponent
---@field Metal_4WayJoint6 UStaticMeshComponent
---@field Metal_4WayJoint7 UStaticMeshComponent
---@field Metal_4WayJoint3 UStaticMeshComponent
---@field Metal_4WayJoint8 UStaticMeshComponent
---@field Metal USceneComponent
---@field Box_CeilingCollision UBoxComponent
---@field Ceiling00 URSTTrapGridBoxComponent
ACeiling_RB_MT_v1_4x4_C = {}
