---@meta

---@class AHub_Blacksmith_BellowsWood_C : AActor
---@field Wood_Plank_300W_A5 UStaticMeshComponent
---@field Wood_Plank_300W_A1 UStaticMeshComponent
---@field Wood_Plank_300W_A3 UStaticMeshComponent
---@field Wood_Plank_300W_A4 UStaticMeshComponent
---@field Wood_Plank_300W_A2 UStaticMeshComponent
---@field Wood_Plank_300W_A UStaticMeshComponent
---@field Wood_Plank_300W_A_Temp_B5 UStaticMeshComponent
---@field Wood_Plank_300W_A_Temp_B4 UStaticMeshComponent
---@field Wood_Plank_300W_A_Temp_B3 UStaticMeshComponent
---@field Wood_Log_900W_A UStaticMeshComponent
---@field Wood_Square_1200W_A1 UStaticMeshComponent
---@field Wood_Platform_300x600_A UStaticMeshComponent
---@field Wood_Plank_300W_A_Temp_B2 UStaticMeshComponent
---@field Wood_Plank_300W_A_Temp_B1 UStaticMeshComponent
---@field Wood_Square_1200W_A UStaticMeshComponent
---@field Wood_Plank_300W_A_Temp_B UStaticMeshComponent
---@field DefaultSceneRoot USceneComponent
AHub_Blacksmith_BellowsWood_C = {}
