---@meta

---@class AHub_Elixir_Tower_C : AActor
---@field SM_MERGED_BP_Library_Bookshelf_2x3_Wall_Merged_Alchemist5 UStaticMeshComponent
---@field SM_MERGED_BP_Library_Bookshelf_2x3_Wall_Merged_Alchemist4 UStaticMeshComponent
---@field SM_MERGED_BP_Library_Bookshelf_2x3_Wall_Merged_Alchemist3 UStaticMeshComponent
---@field SM_MERGED_BP_Library_Bookshelf_2x3_Wall_Merged_Alchemist2 UStaticMeshComponent
---@field SM_MERGED_BP_Library_Bookshelf_2x3_Wall_Merged_Alchemist1 UStaticMeshComponent
---@field SM_MERGED_BP_Library_Bookshelf_2x3_Wall_Merged_Alchemist UStaticMeshComponent
---@field SM_Library_Books_2x3_Merge5 UStaticMeshComponent
---@field SM_Library_Books_2x3_Merge4 UStaticMeshComponent
---@field SM_Library_Books_2x3_Merge3 UStaticMeshComponent
---@field SM_Library_Books_2x3_Merge2 UStaticMeshComponent
---@field SM_Library_Books_2x3_Merge1 UStaticMeshComponent
---@field SM_Library_Books_2x3_Merge UStaticMeshComponent
---@field Cylinder2 UStaticMeshComponent
---@field Stair_2x_90_StoneWallBlock_SM2 UStaticMeshComponent
---@field Cylinder1 UStaticMeshComponent
---@field Stair_2x_90_StoneWallBlock_SM1 UStaticMeshComponent
---@field Cylinder UStaticMeshComponent
---@field Stair_2x_90_StoneWallBlock_SM UStaticMeshComponent
---@field ColumnTrim_CastStone_600W12 UStaticMeshComponent
---@field Dome_3x3_Half_StoneWall_SM14 UStaticMeshComponent
---@field Dome_3x3_Half_StoneWall_SM13 UStaticMeshComponent
---@field Dome_3x3_Half_StoneWall_SM12 UStaticMeshComponent
---@field Dome_3x3_Half_StoneWall_SM11 UStaticMeshComponent
---@field Dome_3x3_Half_StoneWall_SM9 UStaticMeshComponent
---@field Dome_3x3_Half_StoneWall_SM8 UStaticMeshComponent
---@field Dome_3x3_Half_StoneWall_SM7 UStaticMeshComponent
---@field Dome_3x3_Half_StoneWall_SM UStaticMeshComponent
---@field Tower_OctoHalf_3x2_StoneWall_SM5 UStaticMeshComponent
---@field Tower_OctoHalf_3x2_StoneWall_SM4 UStaticMeshComponent
---@field Tower_OctoHalf_3x2_StoneWall_SM3 UStaticMeshComponent
---@field Tower_OctoHalf_3x2_StoneWall_SM2 UStaticMeshComponent
---@field Dome_3x3_B_StoneWall_SM2 UStaticMeshComponent
---@field Dome_3x3_B_StoneWall_SM1 UStaticMeshComponent
---@field ColumnB_CastStone_1Story11 UStaticMeshComponent
---@field ColumnB_CastStone_1Story10 UStaticMeshComponent
---@field ColumnB_CastStone_1Story9 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W3 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W2 UStaticMeshComponent
---@field Wall_4x4x05_Stonewall_SM2 UStaticMeshComponent
---@field Wall_4x4x05_Stonewall_SM1 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W1 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W UStaticMeshComponent
---@field ColumnB_CastStone_1Story7 UStaticMeshComponent
---@field ColumnB_CastStone_1Story5 UStaticMeshComponent
---@field ColumnB_CastStone_1Story4 UStaticMeshComponent
---@field ColumnB_CastStone_1Story3 UStaticMeshComponent
---@field ColumnB_CastStone_1Story2 UStaticMeshComponent
---@field ColumnB_CastStone_1Story1 UStaticMeshComponent
---@field ColumnB_CastStone_1Story UStaticMeshComponent
---@field Floor_4x4_Plaza_PatternD_SM7 UStaticMeshComponent
---@field Floor_4x4_Plaza_PatternD_SM6 UStaticMeshComponent
---@field Floor_4x4_Plaza_PatternD_SM5 UStaticMeshComponent
---@field Floor_4x4_Plaza_PatternD_SM4 UStaticMeshComponent
---@field Floor_4x4_Plaza_PatternD_SM3 UStaticMeshComponent
---@field Floor_4x4_Plaza_PatternD_SM2 UStaticMeshComponent
---@field Floor_4x4_Plaza_PatternD_SM1 UStaticMeshComponent
---@field Floor_4x4_Plaza_PatternD_SM UStaticMeshComponent
---@field DefaultSceneRoot USceneComponent
AHub_Elixir_Tower_C = {}



