---@meta

---@class AHub_Library_WallWindowSeg_B_C : ABP_OMDTrapGrid_C
---@field ColumnTrim_CastStone_600W41 UStaticMeshComponent
---@field ColumnTileB_CastStone_Top9 UStaticMeshComponent
---@field ColumnTileB_CastStone_Top8 UStaticMeshComponent
---@field Cren_Stepped_Square_CS2 UStaticMeshComponent
---@field Cren_Stepped_Square_CS1 UStaticMeshComponent
---@field Cren_Stepped_Short_Five_CS UStaticMeshComponent
---@field Archway_Wall_Top_SM12 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W39 UStaticMeshComponent
---@field Wall_2_2_FB100 UStaticMeshComponent
---@field Archway_Wall_Top_SM11 UStaticMeshComponent
---@field Wall_2_2_angle_FB5 UStaticMeshComponent
---@field ColumnTileB_CastStone_Top7 UStaticMeshComponent
---@field ColumnTileB_CastStone_Top6 UStaticMeshComponent
---@field Wall_2_2_FB_2x_Window1 UStaticMeshComponent
---@field Window_Pointed_Arch_B_SM1 UStaticMeshComponent
---@field Wall_2_2_angle_FB4 UStaticMeshComponent
---@field Collision USceneComponent
---@field Geometry USceneComponent
---@field TrapGrid USceneComponent
AHub_Library_WallWindowSeg_B_C = {}
