---@meta

---@class AHub_Riftroom_Doorway_ClassRoom_C : ABP_OMDTrapGrid_C
---@field ColumnTrim_CastStone_900W1 UStaticMeshComponent
---@field ColumnTrim_CastStone_900W UStaticMeshComponent
---@field Hub_BlackSmith_ArchSmall_SM UStaticMeshComponent
---@field WallTile_4x4_Stonewall_DoorCut_SM UStaticMeshComponent
---@field Wall_2_2_FB77 UStaticMeshComponent
---@field ColumnTrim_CastStone_DoorFrame3 UStaticMeshComponent
---@field Window_Pointed_1x_Trim3 UStaticMeshComponent
---@field Window_Pointed_1x_Trim2 UStaticMeshComponent
---@field Window_Pointed_2x_Trim_Arch1 UStaticMeshComponent
---@field ColumnTrim_CastStone_DoorFrame2 UStaticMeshComponent
---@field ColumnTrim_CastStone_DoorFrame1 UStaticMeshComponent
---@field Window_Pointed_1x_Trim1 UStaticMeshComponent
---@field Window_Pointed_1x_Trim UStaticMeshComponent
---@field ColumnTrim_CastStone_DoorFrame UStaticMeshComponent
---@field Window_Pointed_2x_Trim_Arch UStaticMeshComponent
---@field Column_BaseD_CastStone5 UStaticMeshComponent
---@field Column_BaseD_CastStone16 UStaticMeshComponent
---@field Column_BaseD_CastStone13 UStaticMeshComponent
---@field Column_BaseD_CastStone11 UStaticMeshComponent
---@field Column_BaseD_CastStone10 UStaticMeshComponent
---@field Column_BaseD_CastStone14 UStaticMeshComponent
---@field Floor_2x2_Plaza_PatternA_Trim_SM UStaticMeshComponent
---@field Cren_Stepped_Square_CS UStaticMeshComponent
---@field Column_BaseD_CastStone3 UStaticMeshComponent
---@field Column_BaseD_CastStone2 UStaticMeshComponent
---@field Column_BaseD_CastStone1 UStaticMeshComponent
---@field Column_BaseB_CastStone UStaticMeshComponent
---@field Column_BaseD_CastStone UStaticMeshComponent
---@field Wall_2_2_FB76 UStaticMeshComponent
---@field Collision USceneComponent
---@field Geometry USceneComponent
---@field TrapGrid USceneComponent
AHub_Riftroom_Doorway_ClassRoom_C = {}
