---@meta

---@class UIntroSequence_DryDocks3_DirectorBP_C : ULevelSequenceDirector
---@field UberGraphFrame FPointerToUberGraphFrame
---@field LevelIntro UW_LevelIntro_C
UIntroSequence_DryDocks3_DirectorBP_C = {}

function UIntroSequence_DryDocks3_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_DryDocks3_DirectorBP_0() end
function UIntroSequence_DryDocks3_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_DryDocks3_DirectorBP() end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_DryDocks3_DirectorBP_C:AfterPush_85F7DBD443FE013FEDAA89BDF17195BE(UserWidget) end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_DryDocks3_DirectorBP_C:BeforePush_85F7DBD443FE013FEDAA89BDF17195BE(UserWidget) end
function UIntroSequence_DryDocks3_DirectorBP_C:HideWidget() end
function UIntroSequence_DryDocks3_DirectorBP_C:ShowWidget() end
function UIntroSequence_DryDocks3_DirectorBP_C:HideTheWidget() end
---@param EntryPoint int32
function UIntroSequence_DryDocks3_DirectorBP_C:ExecuteUbergraph_IntroSequence_DryDocks3_DirectorBP(EntryPoint) end


