---@meta

---@class UIntroSequence_Courtyards_Exterior_DirectorBP_C : ULevelSequenceDirector
---@field UberGraphFrame FPointerToUberGraphFrame
---@field ['Level Intro'] UW_LevelIntro_C
UIntroSequence_Courtyards_Exterior_DirectorBP_C = {}

function UIntroSequence_Courtyards_Exterior_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_Courtyards_Exterior_DirectorBP_0() end
function UIntroSequence_Courtyards_Exterior_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_Courtyards_Exterior_DirectorBP() end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_Courtyards_Exterior_DirectorBP_C:AfterPush_56D22A3C4FAB7957B7E08BB82ECC1EF4(UserWidget) end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_Courtyards_Exterior_DirectorBP_C:BeforePush_56D22A3C4FAB7957B7E08BB82ECC1EF4(UserWidget) end
function UIntroSequence_Courtyards_Exterior_DirectorBP_C:ShowWidget() end
function UIntroSequence_Courtyards_Exterior_DirectorBP_C:HideTheWidget() end
function UIntroSequence_Courtyards_Exterior_DirectorBP_C:HideWidget() end
---@param EntryPoint int32
function UIntroSequence_Courtyards_Exterior_DirectorBP_C:ExecuteUbergraph_IntroSequence_Courtyards_Exterior_DirectorBP(EntryPoint) end


