---@meta

---@class UIntroSequence_CastlePlaza_DirectorBP_C : ULevelSequenceDirector
---@field UberGraphFrame FPointerToUberGraphFrame
---@field LevelIntro UW_LevelIntro_C
UIntroSequence_CastlePlaza_DirectorBP_C = {}

function UIntroSequence_CastlePlaza_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_CastlePlaza_DirectorBP_0() end
function UIntroSequence_CastlePlaza_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_CastlePlaza_DirectorBP() end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_CastlePlaza_DirectorBP_C:AfterPush_516935ED452407EF04480CB7234E1F03(UserWidget) end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_CastlePlaza_DirectorBP_C:BeforePush_516935ED452407EF04480CB7234E1F03(UserWidget) end
function UIntroSequence_CastlePlaza_DirectorBP_C:ShowWidget() end
function UIntroSequence_CastlePlaza_DirectorBP_C:HideWidget() end
function UIntroSequence_CastlePlaza_DirectorBP_C:HideTheWidget() end
---@param EntryPoint int32
function UIntroSequence_CastlePlaza_DirectorBP_C:ExecuteUbergraph_IntroSequence_CastlePlaza_DirectorBP(EntryPoint) end


