---@meta

---@class UIntroSequence_Coliseum_DirectorBP_C : ULevelSequenceDirector
---@field UberGraphFrame FPointerToUberGraphFrame
---@field LevelIntro UW_LevelIntro_C
UIntroSequence_Coliseum_DirectorBP_C = {}

function UIntroSequence_Coliseum_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_Coliseum_DirectorBP_0() end
function UIntroSequence_Coliseum_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_Coliseum_DirectorBP() end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_Coliseum_DirectorBP_C:AfterPush_FE5FF1A54D7A7D809035B9B6227AF880(UserWidget) end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_Coliseum_DirectorBP_C:BeforePush_FE5FF1A54D7A7D809035B9B6227AF880(UserWidget) end
function UIntroSequence_Coliseum_DirectorBP_C:ShowWidget() end
function UIntroSequence_Coliseum_DirectorBP_C:HideTheWidget() end
function UIntroSequence_Coliseum_DirectorBP_C:HideWidget() end
---@param EntryPoint int32
function UIntroSequence_Coliseum_DirectorBP_C:ExecuteUbergraph_IntroSequence_Coliseum_DirectorBP(EntryPoint) end


