---@meta

---@class UIntroSequence_BackAlley2_DirectorBP_C : ULevelSequenceDirector
---@field UberGraphFrame FPointerToUberGraphFrame
---@field LevelIntro UW_LevelIntro_C
UIntroSequence_BackAlley2_DirectorBP_C = {}

function UIntroSequence_BackAlley2_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_BackAlley2_DirectorBP_0() end
function UIntroSequence_BackAlley2_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_BackAlley2_DirectorBP() end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_BackAlley2_DirectorBP_C:AfterPush_77EC1EF349440812E80D99A6B04EED51(UserWidget) end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_BackAlley2_DirectorBP_C:BeforePush_77EC1EF349440812E80D99A6B04EED51(UserWidget) end
function UIntroSequence_BackAlley2_DirectorBP_C:ShowWidget() end
function UIntroSequence_BackAlley2_DirectorBP_C:HideTheWidget() end
function UIntroSequence_BackAlley2_DirectorBP_C:HideWidget() end
---@param EntryPoint int32
function UIntroSequence_BackAlley2_DirectorBP_C:ExecuteUbergraph_IntroSequence_BackAlley2_DirectorBP(EntryPoint) end


