---@meta

---@class UIntroSequence_BackAlley3_DirectorBP_C : ULevelSequenceDirector
---@field UberGraphFrame FPointerToUberGraphFrame
---@field LevelIntro UW_LevelIntro_C
UIntroSequence_BackAlley3_DirectorBP_C = {}

function UIntroSequence_BackAlley3_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_BackAlley3_DirectorBP_0() end
function UIntroSequence_BackAlley3_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_BackAlley3_DirectorBP() end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_BackAlley3_DirectorBP_C:AfterPush_E72DE3964A0B6CE163380D8D27584462(UserWidget) end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_BackAlley3_DirectorBP_C:BeforePush_E72DE3964A0B6CE163380D8D27584462(UserWidget) end
function UIntroSequence_BackAlley3_DirectorBP_C:ShowWidget() end
function UIntroSequence_BackAlley3_DirectorBP_C:HideTheWidget() end
function UIntroSequence_BackAlley3_DirectorBP_C:HideWidget() end
---@param EntryPoint int32
function UIntroSequence_BackAlley3_DirectorBP_C:ExecuteUbergraph_IntroSequence_BackAlley3_DirectorBP(EntryPoint) end


