---@meta

---@class UIntroSequence_Patio_InteriorOnly_DirectorBP_C : ULevelSequenceDirector
---@field UberGraphFrame FPointerToUberGraphFrame
---@field ['Level Intro'] UW_LevelIntro_C
UIntroSequence_Patio_InteriorOnly_DirectorBP_C = {}

function UIntroSequence_Patio_InteriorOnly_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_Patio_InteriorOnly_DirectorBP_0() end
function UIntroSequence_Patio_InteriorOnly_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_Patio_InteriorOnly_DirectorBP() end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_Patio_InteriorOnly_DirectorBP_C:AfterPush_16FE62074F040F6C1511E7BC8483C2E6(UserWidget) end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_Patio_InteriorOnly_DirectorBP_C:BeforePush_16FE62074F040F6C1511E7BC8483C2E6(UserWidget) end
function UIntroSequence_Patio_InteriorOnly_DirectorBP_C:ShowWidget() end
function UIntroSequence_Patio_InteriorOnly_DirectorBP_C:HideTheWidget() end
function UIntroSequence_Patio_InteriorOnly_DirectorBP_C:HideWidget() end
---@param EntryPoint int32
function UIntroSequence_Patio_InteriorOnly_DirectorBP_C:ExecuteUbergraph_IntroSequence_Patio_InteriorOnly_DirectorBP(EntryPoint) end


