---@meta

---@class UIntroSequence_BackAlley3_DirectorBP_C : ULevelSequenceDirector
---@field UberGraphFrame FPointerToUberGraphFrame
---@field LevelIntro UW_LevelIntro_C
UIntroSequence_BackAlley3_DirectorBP_C = {}

function UIntroSequence_BackAlley3_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_BackAlley3_DirectorBP_0() end
function UIntroSequence_BackAlley3_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_BackAlley3_DirectorBP() end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_BackAlley3_DirectorBP_C:AfterPush_36174C00473BFED90858348A5AABC2B6(UserWidget) end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_BackAlley3_DirectorBP_C:BeforePush_36174C00473BFED90858348A5AABC2B6(UserWidget) end
function UIntroSequence_BackAlley3_DirectorBP_C:ShowWidget() end
function UIntroSequence_BackAlley3_DirectorBP_C:HideTheWidget() end
function UIntroSequence_BackAlley3_DirectorBP_C:HideWidget() end
---@param EntryPoint int32
function UIntroSequence_BackAlley3_DirectorBP_C:ExecuteUbergraph_IntroSequence_BackAlley3_DirectorBP(EntryPoint) end


