---@meta

---@class UIntroSequence_RestrictedSection_DirectorBP_C : ULevelSequenceDirector
---@field UberGraphFrame FPointerToUberGraphFrame
---@field ['Level Intro'] UW_LevelIntro_C
UIntroSequence_RestrictedSection_DirectorBP_C = {}

function UIntroSequence_RestrictedSection_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_RestrictedSection_DirectorBP_0() end
function UIntroSequence_RestrictedSection_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_RestrictedSection_DirectorBP() end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_RestrictedSection_DirectorBP_C:AfterPush_86F7035041B8B754A2011BB6D011C614(UserWidget) end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_RestrictedSection_DirectorBP_C:BeforePush_86F7035041B8B754A2011BB6D011C614(UserWidget) end
function UIntroSequence_RestrictedSection_DirectorBP_C:ShowWidget() end
function UIntroSequence_RestrictedSection_DirectorBP_C:HideTheWidget() end
function UIntroSequence_RestrictedSection_DirectorBP_C:HideWidget() end
---@param EntryPoint int32
function UIntroSequence_RestrictedSection_DirectorBP_C:ExecuteUbergraph_IntroSequence_RestrictedSection_DirectorBP(EntryPoint) end


