---@meta

---@class UIntroSequence_FishMarket_DirectorBP_C : ULevelSequenceDirector
---@field UberGraphFrame FPointerToUberGraphFrame
---@field LevelIntro UW_LevelIntro_C
UIntroSequence_FishMarket_DirectorBP_C = {}

function UIntroSequence_FishMarket_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_FishMarket_DirectorBP_0() end
function UIntroSequence_FishMarket_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_FishMarket_DirectorBP() end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_FishMarket_DirectorBP_C:AfterPush_EBB1D2C049299CA76BF3029133A21B7A(UserWidget) end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_FishMarket_DirectorBP_C:BeforePush_EBB1D2C049299CA76BF3029133A21B7A(UserWidget) end
function UIntroSequence_FishMarket_DirectorBP_C:HideWidget() end
function UIntroSequence_FishMarket_DirectorBP_C:ShowWidget() end
function UIntroSequence_FishMarket_DirectorBP_C:HideTheWidget() end
---@param EntryPoint int32
function UIntroSequence_FishMarket_DirectorBP_C:ExecuteUbergraph_IntroSequence_FishMarket_DirectorBP(EntryPoint) end


