---@meta

---@class UIntroSequence_BackAlley_Interior_DirectorBP_C : ULevelSequenceDirector
---@field UberGraphFrame FPointerToUberGraphFrame
---@field ['Level Intro'] UW_LevelIntro_C
UIntroSequence_BackAlley_Interior_DirectorBP_C = {}

function UIntroSequence_BackAlley_Interior_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_BackAlley_Interior_DirectorBP_0() end
function UIntroSequence_BackAlley_Interior_DirectorBP_C:SequenceEvent__ENTRYPOINTIntroSequence_BackAlley_Interior_DirectorBP() end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_BackAlley_Interior_DirectorBP_C:AfterPush_B8D7D2DF4840F2B9F56062A6B11D4B89(UserWidget) end
---@param UserWidget UCommonActivatableWidget
function UIntroSequence_BackAlley_Interior_DirectorBP_C:BeforePush_B8D7D2DF4840F2B9F56062A6B11D4B89(UserWidget) end
function UIntroSequence_BackAlley_Interior_DirectorBP_C:ShowWidget() end
function UIntroSequence_BackAlley_Interior_DirectorBP_C:HideTheWidget() end
function UIntroSequence_BackAlley_Interior_DirectorBP_C:HideWidget() end
---@param EntryPoint int32
function UIntroSequence_BackAlley_Interior_DirectorBP_C:ExecuteUbergraph_IntroSequence_BackAlley_Interior_DirectorBP(EntryPoint) end


