---@meta

---@class AStairGroup_4W_B_C : ABP_OMDTrapGrid_C
---@field RailingStairsD1 UStaticMeshComponent
---@field Wall_StoneWall_Castle_2x2_SM1 UStaticMeshComponent
---@field Wall_2x2_StairSide_StoneWall_SM3 UStaticMeshComponent
---@field Wall_2x2_StairSide_StoneWall_SM2 UStaticMeshComponent
---@field Wall_StoneWall_Castle_2x2_SM UStaticMeshComponent
---@field Wall_2x2_StairSide_StoneWall_SM1 UStaticMeshComponent
---@field Wall_2x2_StairSide_StoneWall_SM UStaticMeshComponent
---@field Stair_5x4_StoneWallBlock_SM UStaticMeshComponent
---@field ColumnTrim_CastStone_150W1 UStaticMeshComponent
---@field ColumnTrim_CastStone_150W UStaticMeshComponent
---@field RailingStairsBase_7 UStaticMeshComponent
---@field RailingStairsBase_6 UStaticMeshComponent
---@field RailingStairsBase_5 UStaticMeshComponent
---@field RailingStairsBase_2 UStaticMeshComponent
---@field RailingStairsBase_4 UStaticMeshComponent
---@field RailingStairsBase_3 UStaticMeshComponent
---@field RailingStairsD UStaticMeshComponent
---@field RSTTrapGridBox4 URSTTrapGridBoxComponent
---@field RSTTrapGridBox3 URSTTrapGridBoxComponent
---@field RSTTrapGridBox2 URSTTrapGridBoxComponent
---@field RSTTrapGridBox1 URSTTrapGridBoxComponent
---@field RSTTrapGridBox URSTTrapGridBoxComponent
---@field Geo USceneComponent
---@field TrapGrid USceneComponent
AStairGroup_4W_B_C = {}
