---@meta

---@class AWall_Sewer_4x4_C : ABP_OMDTrapGrid_C
---@field TunnelLarge_Straight_2x_Sewer_SM UStaticMeshComponent
---@field Wall_TunnelHole_4x4_Sewer_SM UStaticMeshComponent
---@field ColumnTrim_CastStone_150W_8 UStaticMeshComponent
---@field ColumnTrim_CastStone_150W_7 UStaticMeshComponent
---@field ColumnTrim_CastStone_150W_6 UStaticMeshComponent
---@field ColumnTrim_CastStone_150W_5 UStaticMeshComponent
---@field ColumnTrim_CastStone_150W_4 UStaticMeshComponent
---@field ColumnTrim_CastStone_150W_3 UStaticMeshComponent
---@field ColumnTrim_CastStone_150W_2 UStaticMeshComponent
---@field ColumnTrim_CastStone_150W_1 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W_4 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W_3 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W_2 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W_1 UStaticMeshComponent
---@field Wall07 URSTTrapGridBoxComponent
---@field Wall06 URSTTrapGridBoxComponent
---@field Wall05 URSTTrapGridBoxComponent
---@field Wall04 URSTTrapGridBoxComponent
---@field Wall03 URSTTrapGridBoxComponent
---@field Wall02 URSTTrapGridBoxComponent
---@field Wall01 URSTTrapGridBoxComponent
---@field Wall00 URSTTrapGridBoxComponent
AWall_Sewer_4x4_C = {}
