---@meta

---@class AWall_Garden_Patio_Corner_C : ABP_OMDTrapGrid_C
---@field Sentinel_Base02_03 UStaticMeshComponent
---@field Floor_1X1_PatternA_Mosaic_SM UStaticMeshComponent
---@field Column_BaseB_CastStone2 UStaticMeshComponent
---@field Column_BaseB_CastStone1 UStaticMeshComponent
---@field Column_BaseB_CastStone UStaticMeshComponent
---@field Stairs_1x_05_SB1 UStaticMeshComponent
---@field Stairs_1x_05_SB UStaticMeshComponent
---@field Stairs_CornerOutside_05_SB UStaticMeshComponent
---@field RailingC1 UStaticMeshComponent
---@field RailingC UStaticMeshComponent
---@field ColumnTileA_CastStone_Top2 UStaticMeshComponent
---@field ColumnTileA_CastStone_Top1 UStaticMeshComponent
---@field ColumnTileA_CastStone_Top UStaticMeshComponent
---@field ColumnTileB_CastStone_Mid1 UStaticMeshComponent
---@field ColumnTileB_CastStone_Mid5 UStaticMeshComponent
---@field ColumnTileB_CastStone_Mid4 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W2 UStaticMeshComponent
---@field SupportBlock6 UStaticMeshComponent
---@field SupportBlock5 UStaticMeshComponent
---@field SupportBlock4 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W UStaticMeshComponent
---@field ColumnTrim_CastStone_300W3 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W1 UStaticMeshComponent
---@field Crenellation_Pointed_Corbel_SM UStaticMeshComponent
---@field ColumnTileB_CastStone_Top2 UStaticMeshComponent
---@field Wall_2_2_FB7 UStaticMeshComponent
---@field Wall_2_2_FB6 UStaticMeshComponent
---@field Wall_2_2_FB5 UStaticMeshComponent
---@field Wall_2_2_FB4 UStaticMeshComponent
---@field Wall_2_2_FB3 UStaticMeshComponent
---@field Wall_2_2_FB2 UStaticMeshComponent
---@field Wall_2_2_FB1 UStaticMeshComponent
---@field Wall_2_2_FB UStaticMeshComponent
---@field ColumnTileB_CastStone_Top1 UStaticMeshComponent
---@field ColumnTileB_CastStone_Top UStaticMeshComponent
---@field ColumnTileB_CastStone_Mid3 UStaticMeshComponent
---@field ColumnTileB_CastStone_Mid2 UStaticMeshComponent
---@field ColumnTileB_CastStone_Mid UStaticMeshComponent
---@field Column_BaseD_CastStone3 UStaticMeshComponent
---@field Column_BaseD_CastStone2 UStaticMeshComponent
---@field Column_BaseD_CastStone UStaticMeshComponent
---@field Wall02 URSTTrapGridBoxComponent
---@field ColumnTrim_CastStone_300W2 UStaticMeshComponent
---@field ColumnTrim_CastStone_300W UStaticMeshComponent
---@field ColumnTrim_CastStone_600W1 UStaticMeshComponent
---@field Wall01 URSTTrapGridBoxComponent
---@field Box_Collision UBoxComponent
---@field Collision USceneComponent
---@field Geometry USceneComponent
---@field TrapGrid USceneComponent
AWall_Garden_Patio_Corner_C = {}



