---@meta

---@class AWindow_3x_Tall_FB_SAND_C : ABP_OMDTrapGrid_C
---@field ColumnTrim_CastStone_150W1 UStaticMeshComponent
---@field ColumnTrim_CastStone_150W UStaticMeshComponent
---@field Window_Pointed_Sil_SM UStaticMeshComponent
---@field Wall_1_3_FB1 UStaticMeshComponent
---@field Wall_1_3_FB UStaticMeshComponent
---@field Window_Pointed_3xB UStaticMeshComponent
---@field ColumnTrim_CastStone_600W4 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W3 UStaticMeshComponent
---@field ColumnTrim_CastStone_900W5 UStaticMeshComponent
---@field ColumnTrim_CastStone_900W4 UStaticMeshComponent
---@field ColumnTrim_CastStone_1200W1 UStaticMeshComponent
---@field ColumnTrim_CastStone_1200W UStaticMeshComponent
---@field ColumnTrim_CastStone_600W2 UStaticMeshComponent
---@field ColumnTrim_CastStone_900W3 UStaticMeshComponent
---@field Wall04 URSTTrapGridBoxComponent
---@field Wall03 URSTTrapGridBoxComponent
---@field Wall02 URSTTrapGridBoxComponent
---@field ColumnTrim_CastStone_900W2 UStaticMeshComponent
---@field ColumnTrim_CastStone_600W1 UStaticMeshComponent
---@field Wall01 URSTTrapGridBoxComponent
---@field Window_CastStone_Tile351 UStaticMeshComponent
---@field Window_CastStone_Sill_Small UStaticMeshComponent
---@field Window_CastStone_Arch350 UStaticMeshComponent
---@field Window_CastStone_Tile350 UStaticMeshComponent
---@field Wall_Sec_2_4_RB5 UStaticMeshComponent
---@field Wall_Sec_2_4_RB4 UStaticMeshComponent
---@field Wall_Sec_2_4_RB3 UStaticMeshComponent
---@field Wall_Sec_2_4_RB2 UStaticMeshComponent
---@field Wall_Sec_2_4_RB1 UStaticMeshComponent
---@field Box_Collision UBoxComponent
---@field Wall_Sec_2_4_RB UStaticMeshComponent
AWindow_3x_Tall_FB_SAND_C = {}
