---@meta

---@class UUI_HUD_C : UUserWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field CanvasSwitcher UWidgetSwitcher
---@field CashText UTextBlock
---@field CMainMenuButton UButton
---@field ControlsBorder UBorder
---@field ControlsButton UButton
---@field CRestartButton UButton
---@field CurrentWave UTextBlock
---@field HealthText UTextBlock
---@field HNextButton UButton
---@field HowToPlayBorder UBorder
---@field HowToPlayButton UButton
---@field HowToPlayImageSwitcher UWidgetSwitcher
---@field HPrevButton UButton
---@field Image_9 UImage
---@field Image_10 UImage
---@field Image_11 UImage
---@field Image_12 UImage
---@field Image_85 UImage
---@field Image_236 UImage
---@field ImageSword UImage
---@field ImageTrap UImage
---@field ImageXbow UImage
---@field LevelCompleteText UTextBlock
---@field NextWaveCountText UTextBlock
---@field NextWaveText UTextBlock
---@field PauseCanvas UCanvasPanel
---@field PContinueButton UButton
---@field PControlsButton UButton
---@field PlayButton UButton
---@field PMainMenuButton UButton
---@field PQuitButton UButton
---@field PressCtoStart UTextBlock
---@field PRestartButton UButton
---@field QuitButton UButton
---@field ReturnButton UButton
---@field ReturnButton2 UButton
---@field RiftPointsText UTextBlock
---@field TotalWaves UTextBlock
---@field TrapCost UTextBlock
---@field TrapNumber UTextBlock
---@field TrapText UTextBlock
---@field WaveClearedText UTextBlock
---@field WeaponNumber UTextBlock
---@field WeaponText UTextBlock
---@field BattleMusic UAudioComponent
UUI_HUD_C = {}

---@param Increment boolean
function UUI_HUD_C:UpdateHTPIndex(Increment) end
---@param Completed int32
---@param Total int32
function UUI_HUD_C:UpdateWaveCounter(Completed, Total) end
---@param Health float
function UUI_HUD_C:UpdateHealth(Health) end
function UUI_HUD_C:WaveClear() end
function UUI_HUD_C:CButtonPressed() end
---@param TimeLeft int32
function UUI_HUD_C:SetNextWaveCountdownText(TimeLeft) end
---@param NewPoints int32
function UUI_HUD_C:UpdateRiftPoints(NewPoints) end
---@param Cash int32
function UUI_HUD_C:UpdateCash(Cash) end
---@param Swing boolean
function UUI_HUD_C:SwingSword(Swing) end
---@param NewTrap Enum_TrapType::Type
---@param TrapCost int32
function UUI_HUD_C:SwitchTrap(NewTrap, TrapCost) end
---@param NewWeapon Enum_Weapons::Type
function UUI_HUD_C:SwitchWeapon(NewWeapon) end
function UUI_HUD_C:Construct() end
function UUI_HUD_C:BndEvt__PlayButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature() end
function UUI_HUD_C:BndEvt__QuitButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature() end
function UUI_HUD_C:BndEvt__HowToPlayButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature() end
---@param bPaused boolean
function UUI_HUD_C:PauseMenu(bPaused) end
function UUI_HUD_C:GameplayHUD() end
---@param Start boolean
function UUI_HUD_C:NextWaveCountdown(Start) end
function UUI_HUD_C:BndEvt__PContinueButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature() end
function UUI_HUD_C:BndEvt__PMainMenuButton_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature() end
function UUI_HUD_C:BndEvt__PQuitButton_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature() end
function UUI_HUD_C:BndEvt__PRestartButton_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature() end
---@param Win boolean
function UUI_HUD_C:LevelCompleted(Win) end
function UUI_HUD_C:BndEvt__CMainMenuButton_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature() end
function UUI_HUD_C:BndEvt__CRestartButton_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature() end
function UUI_HUD_C:BndEvt__ControlsButton_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature() end
function UUI_HUD_C:BndEvt__PControlsButton_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature() end
function UUI_HUD_C:BndEvt__ReturnButton_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature() end
function UUI_HUD_C:BndEvt__ReturnButton2_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature() end
function UUI_HUD_C:BndEvt__HNextButton_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature() end
function UUI_HUD_C:BndEvt__HPrevButton_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature() end
---@param EntryPoint int32
function UUI_HUD_C:ExecuteUbergraph_UI_HUD(EntryPoint) end


